### ISSUE TITLE
Ability to select currency

### ISSUE THREAD

**Issue by povlhp** [MTrab/energidataservice#100]
Currently I have EUR as currency for DK1 / West. Would prefer DKK, and the DKK price is available at energidataservices as part of the dataset. Thus we need a configuration possibility for that. 

We need an example on how to create a local prognosis graph and not just show current price.

**Comment by MTrab** [comment]
Currency follows your settings in your Home Assistant. So if you select DKK as currency in your Home Assistant settings, then prices will be shown in DKK.
