### ISSUE TITLE
New version with Carnot forecast

### ISSUE THREAD

**Issue by Bluhme1** [MTrab/energidataservice#101]
I am testing the new version with the forecast functionality.
As far as I can see, there is a general tendency that the forecast numbers are significantly lower thar the actual prices and the prices for tomorrow. And when the prices for tomorrow are updated at 13.00 they are higher than what was forecasted the day before.

Has it something to do with VAT and the different tariffs? Is the actual prices with tariffs and the forecast prices are without?

Anf thank you for a great job

/Lars

**Comment by MTrab** [comment]
I have nothing to do with Carnot, I just parse their data, which generally seems lower than the actual prices.
