### ISSUE TITLE
[FR]: Add description in Wiki how to show forecast data in apex chart

### ISSUE THREAD

**Issue by donnib** [MTrab/energidataservice#103]
**Is your feature request related to a problem? Please describe.**
 Add description in Wiki how to show forecast data in apex chart

**Describe the solution you'd like**
 Add description in Wiki how to show forecast data in apex chart

**Describe alternatives you've considered**

**Additional context**

**Comment by MTrab** [comment]
https://github.com/MTrab/energidataservice/wiki/Displaying-prices-in-Apexchart-card#option-3---include-forecast-data-in-chart
