### ISSUE TITLE
[FR]: <title>

### ISSUE THREAD

**Issue by ryssel** [MTrab/energidataservice#111]
It would be nice with an example on how to map the information from the buill to values in this page:
https://github.com/MTrab/energidataservice/wiki/How-to-add-costs-of-subscription-and-delivery%3F
I also has Modstrøm (Spot El) and on my last bill it loks like this:
![image](https://user-images.githubusercontent.com/6928064/189125383-8c1f98e5-e457-4ac4-ba6a-3e26ad5e8472.png)

**Comment by MTrab** [comment]
It is purely math gym, and the provided template is only an example on how I do it.
You have all the numbers you need at hand.
