### ISSUE TITLE
Attributterne fra i morgen kommer ikke ind på sensoren

### ISSUE THREAD

**Issue by dsagdfgsFD** [MTrab/energidataservice#115]
Hej. 

I morgen-priserne vises ikke som attribut.. Er det mig der har gjort noget forkert eller er det kendt problem?
(ps. er ikke programmør.)
Og tak for den fede integration. 

------------------
Current price
2,28
Unit
kWh
Currency
DKK
Region
West of the great belt
Region code
DK1
Tomorrow valid
false
Next data update
13:10:04
Today
1.969, 1.963, 1.862, 1.65, 1.616, 1.602, 1.602, 1.667, 1.825, 2.034, 2.307, 2.284, 2.16, 2.041, 1.982, 1.988, 2.01, 2.515, 2.752, 2.947, 2.831, 2.568, 2.311, 2.066
Tomorrow
—
Raw today
- hour: '2022-10-01T00:00:00+02:00'
price: 1.969
- hour: '2022-10-01T01:00:00+02:00'
price: 1.963
- hour: '2022-10-01T02:00:00+02:00'
price: 1.862
- hour: '2022-10-01T03:00:00+02:00'
price: 1.65
- hour: '2022-10-01T04:00:00+02:00'
price: 1.616
- hour: '2022-10-01T05:00:00+02:00'
price: 1.602
- hour: '2022-10-01T06:00:00+02:00'
price: 1.602
- hour: '2022-10-01T07:00:00+02:00'
price: 1.667
- hour: '2022-10-01T08:00:00+02:00'
price: 1.825
- hour: '2022-10-01T09:00:00+02:00'
price: 2.034
- hour: '2022-10-01T10:00:00+02:00'
price: 2.307
- hour: '2022-10-01T11:00:00+02:00'
price: 2.284
- hour: '2022-10-01T12:00:00+02:00'
price: 2.16
- hour: '2022-10-01T13:00:00+02:00'
price: 2.041
- hour: '2022-10-01T14:00:00+02:00'
price: 1.982
- hour: '2022-10-01T15:00:00+02:00'
price: 1.988
- hour: '2022-10-01T16:00:00+02:00'
price: 2.01
- hour: '2022-10-01T17:00:00+02:00'
price: 2.515
- hour: '2022-10-01T18:00:00+02:00'
price: 2.752
- hour: '2022-10-01T19:00:00+02:00'
price: 2.947
- hour: '2022-10-01T20:00:00+02:00'
price: 2.831
- hour: '2022-10-01T21:00:00+02:00'
price: 2.568
- hour: '2022-10-01T22:00:00+02:00'
price: 2.311
- hour: '2022-10-01T23:00:00+02:00'
price: 2.066
Raw tomorrow
—
Today min
hour: '2022-10-01T05:00:00+02:00'
price: 1.602
Today max
hour: '2022-10-01T19:00:00+02:00'
price: 2.947
Today mean
2,11
Tomorrow min
—
Tomorrow max
—
Tomorrow mean
—

**Comment by MTrab** [comment]
Imorgen frigives først mellem 13 og 14

**Comment by MTrab** [comment]
Jeg kan se at din vil opdatere 13.10

**Comment by dsagdfgsFD** [comment]
Giver mening. Beklager :) 

God aften og igen, TAK!
