### ISSUE TITLE
Need raw price attribute

### ISSUE THREAD

**Issue by povlhp** [MTrab/energidataservice#119]
We need a raw price attribute.

I can't calculate a percentage cost pr kWh (I wanted to say 40% tax). 
This works in template preview:
{{ state_attr('sensor.energi_data_service_eksport','current_price') | float * 0.4 }}

But does not work on the entity configuration.

One workaround would be a 3rd raw sensor (confirmed), but that i a bad hack

**Comment by povlhp** [comment]
Would make sense in historic data as well, that we have the raw current data at all times

**Comment by MTrab** [comment]
Add an integration without VAT and with no additional costs - that would show the raw price

**Comment by povlhp** [comment]
Please re-open. 
Now I have 3 sensors - but i get only data for the 2 first due to load / throttling on the server. Last one is almost always unavailable, except if I change something on it. Then it will get updated at another time than the 2 first. 

Having the the raw Price as a property is a trivial change. And would help manage server load at little effort.
