### ISSUE TITLE
[FR]: Add new wiki page with describtion on how to use Eloverblik tariff sensor to calculate prices with tariffs

### ISSUE THREAD

**Issue by baggi97** [MTrab/energidataservice#121]
I have made a wiki page on my fork of the repo with a wiki page with description to use the Eloverblik sensor with tariffs

https://github.com/baggi97/energidataservice/wiki

**Comment by MTrab** [comment]
I don't understand the use - Eloverblik has nothing to do with this integration and is notoriously 48+ hours in the past.

**Comment by baggi97** [comment]
The use case is that in the newest version of eloverblik they have added a sensor that displays the current tariffs of the entire day for the meters therefore it will be possible to use this sensor as the added cost and removes the need for manually inputting the additional cost.

But yes maybe one could argue that the wiki page should be updated in eloverblik with an example of how to use this new sensor with this integration - I just thought that this information might be relevant for users of the integration as well - and as it is a wiki example it is not implementing anything in the code and might help some users.

**Comment by MTrab** [comment]
But again - this integration can't even be used with eloverblik because of the delay in data.

**Comment by baggi97** [comment]
Not completely true for my suggestion - the new sensor is not based on the live data, but based on the user's meter data, and therefore this sensor is always up to date with the newest prices for additional costs

I'm only suggesting a wiki page for helping users who wants a template for getting dynamic additional costs in - that is why I also created the wiki page in my fork for you to not have to do anything - but if you do not agree that this wiki page could be of any help, that is fine :)

**Comment by askpet** [comment]
Just a POV: {{ states('sensor.eloverblik_tariff_sum') }} from Eloverblik is fantastic. No more templates for aditional cost. No need for you to try and understand the complete list from all vendors. Its all delivered directly.

Regarding historic data and 2-5 days old data - completely agree - useless (in the context og Energidataservice)

**Comment by MTrab** [comment]
Just read up on code for the tariffs from eloverblik. It does NOT include subscription and fees, so you still need more than you added in the forked wiki.

**Comment by MTrab** [comment]
I'm going to close this, as I cannot recommend this way of getting the additional costs.
It's based on historical data and does not include all additional costs.

Great idea thou, but not great enough that I'll recommend it without several disclaimers.

**Comment by baggi97** [comment]
I think this is fine - the tariffs are not based on historical data, but all understand the fact on missing prices, which I actually added to my template in the forked wiki
