### ISSUE TITLE
[FR]: Both elspot price entity and a calculated selling price entity and a calculated buying price entity

### ISSUE THREAD

**Issue by osos** [MTrab/energidataservice#122]
Det bliver lige på dansk.

Vi har solceller. Det betyder, at vi sælger strøm til elspot-pris minus transport og omkostning (https://www.vindstoed.dk/tilmelding-solcelle)

Vi vil derfor gerne se, salgspris og købspris. Begge er en funktion af elspot-prisen, men med to forskellige beregninger.

Foreslår derfor, at din component tilbyder tre entities i HA. elspot-entity (ren data fra Energi Data Service), calculated-buying-price, calculated-selling-price.

**Comment by MTrab** [comment]
Du kan oprette lige så mange sensorer du vil, med hver deres template

**Comment by osos** [comment]
Ja, men det ville da gøre din component mere tilgængelig for de fleste. Det ville være en lækker og brugervenlig tilgang, hvis du kunne levere den løbende og forudsete reelle pris.

Allerbedst hvis den selv kan trække data til priserne. 

Hvorfra har du data for afgifter, transport m.v.? (https://github.com/MTrab/energidataservice/wiki/How-to-add-costs-of-subscription-and-delivery%3F)

**Comment by MTrab** [comment]
Men alt det du spørger efter, det skulle den allerede kunne. Det er jo blot et spørgsmål om dine templates.

Og værdierne?! Fra min elregning

**Comment by osos** [comment]
Men jeg ønsker jo ikke at lave templates, og det er advanceret for mange brugere.

Jeg vil hellere konfigurere din component med beregningsdata for henholdsvis køb og salg af strøm, og at komponenten så stiller det til rådighed som entities. Dem kan jeg nemt og uden yaml sætte ind i HA's energipanel.

Det vil gøre det mere brugervenligt. Og lettere for almindelige (amatør)brugere at få gang i det.

Tak for tippet med elregningen. Fandt også Dinel's tarif på deres hjemmeside: https://dinel.dk/priser-og-bestemmelser/ Det kunne du eventuelt tilføje til din wiki.

**Comment by MTrab** [comment]
Men det er jo også netop det jeg skriver. Det du spørger efter, det er allerede muligt.
Det er et spørgsmål om hvordan du konfigurerer integrationen.

**Comment by osos** [comment]
Ok, så er det nok bare mig der ikke har fanget hvordan.

**Comment by MTrab** [comment]
Som skrevet: Du kan tilføje så mange instanser af integrationen du vil, alle med hver sin konfiguration og additional cost template

**Comment by osos** [comment]
Hold nu op.... det havde jeg simpelthen ikke set. Min fejl. Beklager at være så tungnem. Tak for tålmodigheden :-)
