### ISSUE TITLE
[FR]: Make it possible to use with fixed price contracts

### ISSUE THREAD

**Issue by MTrab** [MTrab/energidataservice#125]
Make it possible to use fixed price contracts but present a full 24/48 hours with added additional costs template added to the price.

**Comment by OldSmurf56** [comment]
Yes! That would be so nice :-) I installed EDS already, so as soon as you include this feature ... 
BTW - just to make it more challenging - I also have a heat pump so I only pay taxes on the first 4.000kWh.
PS - @MTrab - I am amazed by your work and efforts (here and on FB). You are simple AWESOME!

**Comment by MTrab** [comment]
This makes absolutely no sense to this integration, as fixed price contracts is already possible with native Home Assistant template sensors.
This integration is for spotprice only.

**Comment by MTrab** [comment]
Will be implemented in version 1.0.0
