### ISSUE TITLE
Template for extra costs not working after restart

### ISSUE THREAD

**Issue by kibuan** [MTrab/energidataservice#126]
When I restart Home Assistant the "Template for extra costs (Skabelon for ekstra omkostninger)" is not being added to the price. Reloading Energidata service integration solves the issue.

**Comment by MTrab** [comment]
Anything in the logs?

And please attach your additional costs template

**Comment by kibuan** [comment]
My template is: 

{{ state_attr('sensor.eloverblik_tariff_sum','hourly')[now().hour] }}

Could it be that the sensor from eloverblik is yet not available when Energidata service loads after a restart?

Nothing of interest in the log.

**Comment by MTrab** [comment]
Yes - that is a non-supported template, and if the sensor data in the template is not available, then you have your answer.
