### ISSUE TITLE
[FR]: Use DKK instead of EUR

### ISSUE THREAD

**Issue by smulle48** [MTrab/energidataservice#127]
**Is your feature request related to a problem? Please describe.**
When using the EUR value and let HA convert it, it does not reflect the official price from NordPool at the time, and it's also off, compared with the DKK value from the dataset

**Describe the solution you'd like**
Instead of blindly convert from EUR to DKK, this plugin already gets the correct country code (DKK). Why not use that instead when polling the data and just use the correct values without any conversion at all.

If exchange rates were to be used, they should be polled from NordPool instead, which already shows them for each day

**Comment by MTrab** [comment]
DKK prices are only available during business days.
So the answer will be no.
We'll keep using EUR as the base for the prices.

**Comment by smulle48** [comment]
Maybe you should add an disclaimer that your plugin is using the build in currency converter, and thereby not the correct converted price. Only the price in EUR is guaranteed to be correct.
