### ISSUE TITLE
Integration not updating

### ISSUE THREAD

**Issue by hauard** [MTrab/energidataservice#129]
Integration not updating, getting error:
![Screenshot_20221115-002207_Home Assistant](https://user-images.githubusercontent.com/112585314/201788574-12b4ee52-6838-466f-a0af-e433a6f25d8d.jpg)

My system information:
`
## System Information

version | core-2022.11.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.61-v8
arch | aarch64
timezone | Europe/Oslo
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4912
Installed Version | 1.28.3
Stage | running
Available Repositories | 1142
Downloaded Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.3
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.2
agent_version | 1.4.1
docker_version | 20.10.18
disk_total | 28.6 GB
disk_used | 10.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), Node-RED (13.5.2), SSH & Web Terminal (12.1.2), Home Assistant Google Drive Backup (0.109.1), File editor (5.4.2), Log Viewer (0.14.0), Mosquitto broker (6.1.3), Let's Encrypt (4.12.7), NGINX Home Assistant SSL proxy (3.1.5), Grafana (8.1.0), InfluxDB (4.5.0), AppDaemon (0.10.0), MQTT IO (0.1.3), Glances (0.17.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 4
views | 9
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 9. november 2022 kl. 20:13
-- | --
current_recorder_run | 9. november 2022 kl. 21:49
estimated_db_size | 331.26 MiB
database_engine | sqlite
database_version | 3.38.5

</details>
`

**Comment by hauard** [comment]
Integration is updating now, could it have been an error at source-API ?

**Comment by MTrab** [comment]
Yes, seems like a connection error or an error in the API response.
That's why it retried so many times - build in failsafe in the integration ;)

**Comment by hauard** [comment]
Hi, the integration is not updating again today. Someone else have the same issue?
 I see a bug stating that 'fallback to Nordpool not working,' my log says nothing about this.

But why the need for two different sources? Are EDS unstable? Redundancy? More options in the data pulled from EDS?

**Comment by MTrab** [comment]
There's no data in the API for tomorrow, so not an issue in the integration.

**Comment by MTrab** [comment]
The Nordpool was ment as a fallback in case Energi Data Service failed for some reason.
The data is the same.
But for an yet to be discovered reason, the fallback is not kicking in as intended
