### ISSUE TITLE
Weird behavior in forecast prices

### ISSUE THREAD

**Issue by fbjerggaard** [MTrab/energidataservice#133]
Sometimes the forecasted prices makes the graphs look a bit weird:

![image](https://user-images.githubusercontent.com/1044024/205123935-cbeffa0f-4d41-4a2e-8520-fdae70948571.png)

### Environment:
Home Assistant 2022.11.5 - running in Docker

## Configuration
Country: Denmark
Region: DK2
Show in cents: No
Number of decimals: 3

## Additional cost template
```text
{% set costs = {"elafgift": 0.763,"nettarif_lav": 0.3028,"nettarif_spids": 0.7885,"abonnement_net": 0.0685,"eltillaeg_ellev": 0.00,"abonnement_ellev": 0.047} %}{% if now().month >= 10 or now().month < 4 %}{% if now().hour >= 17 and now().hour < 20 %} {{costs.elafgift +costs.nettarif_spids +costs.abonnement_net +costs.eltillaeg_ellev +costs.abonnement_ellev }}{% else %} {{costs.elafgift +costs.nettarif_lav +costs.abonnement_net +costs.eltillaeg_ellev +costs.abonnement_ellev }}{% endif %} {% else %} {{costs.elafgift +costs.nettarif_lav +costs.abonnement_net +costs.eltillaeg_ellev +costs.abonnement_ellev }} {% endif %}
```

## Describe the bug
Looking into the entity attributes it seems like the forecast data is either not cleared correctly or is loading wrong data - see snippet of attributes:
```text
forecast: 
- hour: '2022-11-30T16:00:00+01:00'
  price: 5.924
- hour: '2022-11-30T17:00:00+01:00'
  price: 6.764
- hour: '2022-11-30T18:00:00+01:00'
  price: 6.687
- hour: '2022-11-30T19:00:00+01:00'
  price: 6.407
- hour: '2022-11-30T20:00:00+01:00'
  price: 5.324
- hour: '2022-11-30T21:00:00+01:00'
  price: 4.676
- hour: '2022-11-30T22:00:00+01:00'
  price: 4.422
- hour: '2022-11-30T23:00:00+01:00'
  price: 4.053
- hour: '2022-12-03T00:00:00+01:00'
  price: 3.897
- hour: '2022-12-03T01:00:00+01:00'
  price: 3.896
- hour: '2022-12-03T02:00:00+01:00'
  price: 3.849
- hour: '2022-12-03T03:00:00+01:00'
  price: 3.859
```

**Comment by MTrab** [comment]
Something is odd, indeed

**Comment by KDYR** [comment]
I saw the same. And btw, tomorrow's prices have been missing for me since then.

**Comment by MTrab** [comment]
It's related to the issues Energi Data Service has experienced with their API the last week or so.
It affects the integration as it struggles to retrieve data and it affects Carnot's forecast models as well.

I'll do my best to make a fix for the integration, but for the Carnot data I cannot do much.

**Comment by KDYR** [comment]
Thanks for info! and thanks for your continued efforts and contributions!
