### ISSUE TITLE
Not updating as expected

### ISSUE THREAD

**Issue by sorenbo** [MTrab/energidataservice#135]
Normally the data have refreshed each day at around 13.00 however this is not the case since Dec. 3rd I can see new data on Energidata service but they don't load in HA. 

Log
This error originated from a custom integration.

Logger: custom_components.myenergi
Source: helpers/update_coordinator.py:151
Integration: myenergi (documentation, issues)
First occurred: December 3, 2022 at 19:23:47 (8 occurrences)
Last logged: 15:48:25

Error fetching myenergi data:

Any idea on how to troubleshoot more?

**Comment by MTrab** [comment]
This is an error in the Energi Data Service API and out of my hands
