### ISSUE TITLE
v0.4.7 still fails at day change

### ISSUE THREAD

**Issue by ryssel** [MTrab/energidataservice#148]
- Home Assistant version: 2022.12.6
- Energidatastyrelsen version: Where do i find this?
- Operation system: HAOS 9.4

- Country: Denmark
- Region: East of the great belt
- Show in cents: No
- Number of decimals: 3
- 
Restarting makes work until next day change
![image](https://user-images.githubusercontent.com/6928064/207847448-1215b2f2-f1bc-48d9-b57d-3bc5be1fef94.png)
[config_entry-energidataservice-7264a80da94ee143a90bd12657058951.json.txt](https://github.com/MTrab/energidataservice/files/10236568/config_entry-energidataservice-7264a80da94ee143a90bd12657058951.json.txt)

**Comment by MTrab** [comment]
Confirmed - but still, please provide all information as requested in the issue template!
