### ISSUE TITLE
FR: Statistics

### ISSUE THREAD

**Issue by JBoye** [MTrab/energidataservice#15]
Så vidt jeg kan se er det kun `state_class: measurement` som attribute der mangler for at HA kan gemme priser som long-term statistics. 

Det har lidt begrænset funktion nu, men på længere sigt vil det være interessant at kunne se statistik over

**Comment by MTrab** [comment]
Ser ikke ud til at det er nok - har tilføjet det på min dev udgave, men den registrerer sig ikke under statestik.

Jeg kigger lige på hvad der ellers skal til

**Comment by JBoye** [comment]
Underligt... 
Hvis jeg manuelt tilføjer `state_class: measurement` under Developer Tools > States så dukker den ellers fint op under Developer Tools > statistics med "No issue" (Indtil integrationen overskriver attributes igen)

**Comment by MTrab** [comment]
Jep - har lige fundet fejlen :)
Det kommer med i næste release.
