### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by Bluhme1** [MTrab/energidataservice#156]
## Error in log

Example:
- Home Assistant version: 2022.12.7
- Energidataservice version: 0.4.9
- Operation system: HAOS

Example:
- Country: Denmark
- Region: West of the great belt
- Show in cents: Yes/No
- Number of decimals

## Describe the bug
The following shows in the log. I don't think it effects functionality

## Debug log

<Integration MTrab/forsyning> GitHub returned 404 for https://api.github.com/repos/MTrab/forsyning

```

**Comment by MTrab** [comment]
Tjek lige hvad du skriver ;) Tænker du måske selv kan se fejlen ;)
Hint: Forsyning != Energidataservice
