### ISSUE TITLE
Where to find alle the values?

### ISSUE THREAD

**Issue by amnesia-drop** [MTrab/energidataservice#161]
Hi,

I am new to this, and could not find any answer regardless of where I looked for it.

Where do I find the correct value for the Andel Energi?

 "elafgift": 0.763,
    "nettarif_lav": 0.1636,
    "nettarif_spids": 0.4537,
    "abonnement_net": 0.09425,
    "eltillaeg_ellev": 0.07,
    "abonnement_ellev": 0.725

I use default values, and the price does not match at all. If I use the price with MOMS, the difference is even greater. Please help.

**Comment by MTrab** [comment]
First off.
As stated in the wiki - The additional costs template is WITHOUT VAT.

As for the numbers. Your bill could be a way to find your expenses. Your your suppliers home page.
Ultimately you could try elspotpris.dk - but not sure how accurate that page is.

**Comment by amnesia-drop** [comment]
The only value I can find is elafgift. None of the other values can be found, at least not under those names.

Elafgift - 0,723 kr.
Balancetarif for forbrug - 0,00229 kr.
Systemtarif - 0,061 kr.
Transmissions nettarif - 0,049 kr.

So there is something missing here, and that is what I am trying to figure out. Thanks.

**Comment by MTrab** [comment]
Perhaps you don't need other values, I cannot tell you as I have no knowledge of the agreement you have with your electrical company.
Just remember, the wiki template is only an example and might not be correct for your need.
It's just simple Jinja templates like the rest of Home Assistant templates.
