### ISSUE TITLE
Rounding issue

### ISSUE THREAD

**Issue by systemedz** [MTrab/energidataservice#162]
When configuring the integration, it asks for Decimals.
If I set the decimal to 2, I would expect that it gives me 2 decimals, but it seems like it is rounding the decimals which gives me wrong outputs.

I want 2 decimals without rounding, so if the spotprice right now is 3.196 DKK, I want 3.19 DKK and not 3.20 DKK (which turns into 3.2 DKK).

If I look at the price at e.g. elspotpris.dk, the price pr kWh today @ 17:00 in DK1 is 3,19 DKK (including tarrifs, VAT etc.). Looking at the same time in HA, it shows 3.2 DKK.

I know that we're talking small numbers here, but it could potentially be ~50 DKK / year in my case.. or ~4 DKK / month which could be avoided by simply giving me the option to disable rounding of the decimals in the integration configuration.

Would it be possible to add this as a configuration option in a near future?

Thanks!

**Comment by MTrab** [comment]
Valid point you got there - never thought of just removing the extra decimals rather than round them.
I'll look into this and see how I can implement this the best

**Comment by kfjellerup** [comment]
But won't it give a bigger error to not round? 
In your example with a spot price of 3.196, rounding to two decimals (3.20) gives an "error" of 0.004, while removing the last digit (3.19) gives an error of 0.006.

**Comment by systemedz** [comment]
> 

Obviously, that could also cause an issue. So an option would be to implement an optional rounding, and then decide if it should round up or down as a configurable option.

I am not sure if there is a standard on how energy companies does this. Clearly, they don't add all decimals (usually 4 decimals) on an invoice. But I am not sure if they round up or down.

But when using the energy dashboard in HA, and you want it to calculate the price of the consumed energy, you want it to be as close to the electricity bill as possible.

**Comment by kfjellerup** [comment]
I would guess that they do not round at all on an hourly basis, but only on monthly basis when they need to report the average price on the receipt?
So to get as close as possible to that, have as many decimals as possible HA :)

**Comment by askpet** [comment]
I would be surprised if a vendor rounds to 2 decimals for total price calculations. That would be both absolutely wrong and odd.

Before changing the way Energi Data Service rounds ( which is the correct way of rounding) I suggest that Kenneth checks his vendor of their rounding habits.

Hope I am making sense

/Anders

**Comment by AMajland** [comment]
When i export from eloverblik the number of digits is less that what i see on my sale of electricty.  There i get 
- 3 digits on the sale [kWh/hour] i.e a resolution of 1Wh
- 5 digits on the price in kr/kWh
- 8 digits on the price for each hour [kr]

Imho no need to round anything in energidataservice.

I think it is a UI issue to get values shown with a fixed number of digits and it also ticks my small OCD when numbers like 1,00 amd and 1,01 will be shown as
1
1,01 as defualt

**Comment by MTrab** [comment]
Okay - think I'll go for a design with 3 options.

- Round
- Remove excess decimals
- Do nothing

Thin I think we'll cover almost every wish for the value :D

**Comment by jippi** [comment]
my hot take: Never ever round the number in the datastore / state - round/cut the number when you present it in the UI instead. 

Thats how *all* financial data is treated. Store it in cents, never round it outside maybe 6-10 digits, and do your data manipulation when presenting the data in browser/API. 

All kind of messed up things happen when you round values, especially once you start doing averages, sum, percentiles and so on.

**Comment by MTrab** [comment]
All handling (rounding or not) will now be handled by the native Home Assistant engine and is as such not in scope of this integration as pr. HA version 2023.3.0
