### ISSUE TITLE
Choosing N1 as operator renders an error

### ISSUE THREAD

**Issue by DKFrederik** [MTrab/energidataservice#178]
## Configuration

Example:
- Country: fastpris
- Region: West of the great belt
- Show in cents: No
- Number of decimals: 3

## Additional cost template

{{0.0|float}}

## Describe the bug
sensor.energi_data_service is not beings setup correctly

When looking at the sensor this description shows up.
This entity is no longer being provided by the energidataservice integration. If the entity is no longer in use, delete it in settings.

## Debug log

```text

-------------------------------------------------------------------
Energi Data Service integration

Version: 1.0.0
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/mtrab/energidataservice/issues
-------------------------------------------------------------------

2023-01-08 10:35:23.599 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.energidataservice
2023-01-08 10:35:23.892 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.energidataservice entity: sensor.energi_data_service
2023-01-08 10:35:24.116 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform energidataservice
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 709, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 803, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/energidataservice/sensor.py", line 408, in async_added_to_hass
    await self.validate_data()
  File "/config/custom_components/energidataservice/sensor.py", line 257, in validate_data
    await self._api.update()
  File "/config/custom_components/energidataservice/__init__.py", line 309, in update
    await self.async_get_tariffs()
  File "/config/custom_components/energidataservice/__init__.py", line 355, in async_get_tariffs
    self.tariff_data = await tariff.async_get_tariffs()
  File "/config/custom_components/energidataservice/tariffs/energidataservice/__init__.py", line 96, in async_get_tariffs
    (entry["ValidTo"].split("T"))[0] >= end_date or entry["ValidTo"] is None
AttributeError: 'NoneType' object has no attribute 'split'
2023-01-08 10:35:24.117 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up energidataservice platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 297, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 709, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 803, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/energidataservice/sensor.py", line 408, in async_added_to_hass
    await self.validate_data()
  File "/config/custom_components/energidataservice/sensor.py", line 257, in validate_data
    await self._api.update()
  File "/config/custom_components/energidataservice/__init__.py", line 309, in update
    await self.async_get_tariffs()
  File "/config/custom_components/energidataservice/__init__.py", line 355, in async_get_tariffs
    self.tariff_data = await tariff.async_get_tariffs()
  File "/config/custom_components/energidataservice/tariffs/energidataservice/__init__.py", line 96, in async_get_tariffs
    (entry["ValidTo"].split("T"))[0] >= end_date or entry["ValidTo"] is None
AttributeError: 'NoneType' object has no attribute 'split'

```

## Diganostics data from the device

```text

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.1.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Copenhagen",
    "os_name": "Linux",
    "os_version": "5.15.80",
    "supervisor": "2022.12.1",
    "host_os": "Home Assistant OS 9.4",
    "docker_version": "20.10.19",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "landroid_cloud": {
      "version": "2.3.4",
      "requirements": [
        "pyworxcloud==2.1.23"
      ]
    },
    "hacs": {
      "version": "1.29.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "aula": {
      "version": "0.1.26",
      "requirements": [
        "beautifulsoup4",
        "lxml"
      ]
    },
    "nordpool": {
      "version": "0.0.9",
      "requirements": [
        "nordpool>=0.2"
      ]
    },
    "energidataservice": {
      "version": "1.0.0",
      "requirements": [
        "CurrencyConverter==0.17.4",
        "pyeloverblik==0.3.1"
      ]
    },
    "sonoff": {
      "version": "3.3.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "renoweb": {
      "version": "0.1.16",
      "requirements": [
        "pyrenoweb==0.2.3"
      ]
    },
    "eloverblik": {
      "version": "0.2.0",
      "requirements": [
        "pyeloverblik==0.3.1"
      ]
    },
    "fuelprices_dk": {
      "version": "1.6",
      "requirements": [
        "beautifulsoup4",
        "html.parser"
      ]
    },
    "reolink_rest": {
      "version": "0.6.7",
      "requirements": [
        "async-reolink.rest==0.6.6"
      ]
    },
    "localtuya": {
      "version": "4.1.1",
      "requirements": []
    },
    "mbapi2020": {
      "version": "0.7.4",
      "requirements": [
        "protobuf>=3.19.1,<4"
      ]
    }
  },
  "integration_manifest": {
    "after_dependencies": [
      "http"
    ],
    "codeowners": [
      "@MTrab"
    ],
    "config_flow": true,
    "documentation": "https://github.com/MTrab/energidataservice/blob/master/README.md",
    "domain": "energidataservice",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/MTrab/energidataservice/issues",
    "name": "Energi Data Service",
    "requirements": [
      "CurrencyConverter==0.17.4",
      "pyeloverblik==0.3.1"
    ],
    "version": "1.0.0",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "8d85f602db27384c657f535e0b38b0aa",
      "version": 1,
      "domain": "energidataservice",
      "title": "Energi Data Service",
      "data": {
        "name": "Energi Data Service"
      },
      "options": {
        "tariff_charge_owner": "N1 A/S - 344",
        "enable_forecast": false,
        "enable_tariffs": true,
        "fixed_value": 3440.0,
        "vat": true,
        "in_cent": false,
        "decimals": 3,
        "pricetype": "kWh",
        "cost_template": "{{0.0|float}}",
        "name": "Energi Data Service",
        "country": "Fixed Price"
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "**REDACTED**",
      "disabled_by": null
    },
    "today": [
      [
        3440.0,
        "2023-01-08T01:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T02:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T03:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T04:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T05:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T06:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T07:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T08:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T09:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T10:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T11:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T12:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T13:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T14:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T15:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T16:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T17:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T18:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T19:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T20:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T21:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T22:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T23:00:00+01:00"
      ]
    ],
    "today_calculated": false,
    "api_today": [
      [
        3440.0,
        "2023-01-08T01:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T02:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T03:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T04:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T05:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T06:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T07:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T08:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T09:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T10:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T11:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T12:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T13:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T14:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T15:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T16:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T17:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T18:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T19:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T20:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T21:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T22:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-08T23:00:00+01:00"
      ]
    ],
    "tomorrow": [
      [
        3440.0,
        "2023-01-09T01:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T02:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T03:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T04:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T05:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T06:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T07:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T08:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T09:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T10:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T11:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T12:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T13:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T14:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T15:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T16:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T17:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T18:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T19:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T20:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T21:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T22:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T23:00:00+01:00"
      ]
    ],
    "tomorrow_calculated": false,
    "api_tomorrow": [
      [
        3440.0,
        "2023-01-09T01:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T02:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T03:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T04:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T05:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T06:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T07:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T08:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T09:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T10:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T11:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T12:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T13:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T14:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T15:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T16:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T17:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T18:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T19:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T20:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T21:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T22:00:00+01:00"
      ],
      [
        3440.0,
        "2023-01-09T23:00:00+01:00"
      ]
    ],
    "predictions": null,
    "api_predictions": null,
    "tariff_data": null,
    "next_update": "13:36:11",
    "data_source": "Fixed Price",
    "home_assistant_tz": "Europe/Copenhagen",
    "home_assistant_currency": "DKK"
  }
}

```

**Comment by dartfrogdk** [comment]
Har samme problem

**Comment by MTrab** [comment]
> Har samme problem

Samme fejl i loggen? I så fald, vedhæft lige dit diagnostic for enheden.
Hvis ikke, så opret et issue med din fejl.

**Comment by Coolltazz** [comment]
Logger: homeassistant.components.sensor
Source: custom_components/energidataservice/sensor.py:582
Integration: Sensor (documentation, issues)
First occurred: 13.03.21 (2 occurrences)
Last logged: 13.03.21

Error adding entities for domain sensor with platform energidataservice
Error while setting up energidataservice platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 788, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/energidataservice/sensor.py", line 408, in async_added_to_hass
    await self.validate_data()
  File "/config/custom_components/energidataservice/sensor.py", line 259, in validate_data
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/energidataservice/sensor.py", line 618, in _format_list
    price = self._calculate(
  File "/config/custom_components/energidataservice/sensor.py", line 582, in _calculate
    price += float(self._api.tariff_data["tariffs"][str(hour.hour)]) * (
KeyError: '0'


{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.12.8",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Copenhagen",
    "os_name": "Linux",
    "os_version": "5.15.76-v8",
    "supervisor": "2022.12.1",
    "host_os": "Home Assistant OS 9.4",
    "docker_version": "20.10.19",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "panasonic_cc": {
      "version": "1.0.32",
      "requirements": []
    },
    "audiconnect": {
      "version": "2021.1.1",
      "requirements": [
        "beautifulsoup4"
      ]
    },
    "hacs": {
      "version": "1.29.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "blueiris": {
      "version": "1.0.15",
      "requirements": []
    },
    "ihc": {
      "version": "2022.10.0",
      "requirements": [
        "defusedxml==0.6.0",
        "ihcsdk==2.7.6"
      ]
    },
    "energidataservice": {
      "version": "1.0.0",
      "requirements": [
        "CurrencyConverter==0.17.4",
        "pyeloverblik==0.3.1"
      ]
    }
  },
  "integration_manifest": {
    "after_dependencies": [
      "http"
    ],
    "codeowners": [
      "@MTrab"
    ],
    "config_flow": true,
    "documentation": "https://github.com/MTrab/energidataservice/blob/master/README.md",
    "domain": "energidataservice",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/MTrab/energidataservice/issues",
    "name": "Energi Data Service",
    "requirements": [
      "CurrencyConverter==0.17.4",
      "pyeloverblik==0.3.1"
    ],
    "version": "1.0.0",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "057273438e2a631393cdc6e5feb8df0e",
      "version": 1,
      "domain": "energidataservice",
      "title": "Energi Data Service",
      "data": {
        "name": "Energi Data Service"
      },
      "options": {
        "enable_forecast": false,
        "area": "East of the great belt",
        "vat": true,
        "in_cent": false,
        "decimals": 3,
        "pricetype": "kWh",
        "cost_template": "{{0|float}}",
        "name": "Energi Data Service",
        "country": "Denmark",
        "email": "**REDACTED**",
        "api_key": "**REDACTED**",
        "enable_tariffs": true,
        "tariff_charge_owner": "Radius Elnet AS"
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "**REDACTED**",
      "disabled_by": null
    },
    "today": [
      [
        24.440001,
        "2023-01-08T00:00:00+01:00"
      ],
      [
        9.3,
        "2023-01-08T01:00:00+01:00"
      ],
      [
        9.1,
        "2023-01-08T02:00:00+01:00"
      ],
      [
        4.16,
        "2023-01-08T03:00:00+01:00"
      ],
      [
        5.58,
        "2023-01-08T04:00:00+01:00"
      ],
      [
        9.92,
        "2023-01-08T05:00:00+01:00"
      ],
      [
        9.02,
        "2023-01-08T06:00:00+01:00"
      ],
      [
        16.469999,
        "2023-01-08T07:00:00+01:00"
      ],
      [
        27.08,
        "2023-01-08T08:00:00+01:00"
      ],
      [
        29.08,
        "2023-01-08T09:00:00+01:00"
      ],
      [
        35.220001,
        "2023-01-08T10:00:00+01:00"
      ],
      [
        70.190002,
        "2023-01-08T11:00:00+01:00"
      ],
      [
        49.080002,
        "2023-01-08T12:00:00+01:00"
      ],
      [
        65.129997,
        "2023-01-08T13:00:00+01:00"
      ],
      [
        62.189999,
        "2023-01-08T14:00:00+01:00"
      ],
      [
        63.490002,
        "2023-01-08T15:00:00+01:00"
      ],
      [
        86.290001,
        "2023-01-08T16:00:00+01:00"
      ],
      [
        118.040001,
        "2023-01-08T17:00:00+01:00"
      ],
      [
        122.610001,
        "2023-01-08T18:00:00+01:00"
      ],
      [
        65.620003,
        "2023-01-08T19:00:00+01:00"
      ],
      [
        60.98,
        "2023-01-08T20:00:00+01:00"
      ],
      [
        60.310001,
        "2023-01-08T21:00:00+01:00"
      ],
      [
        69.400002,
        "2023-01-08T22:00:00+01:00"
      ],
      [
        48.889999,
        "2023-01-08T23:00:00+01:00"
      ]
    ],
    "today_calculated": false,
    "api_today": [
      [
        24.440001,
        "2023-01-08T00:00:00+01:00"
      ],
      [
        9.3,
        "2023-01-08T01:00:00+01:00"
      ],
      [
        9.1,
        "2023-01-08T02:00:00+01:00"
      ],
      [
        4.16,
        "2023-01-08T03:00:00+01:00"
      ],
      [
        5.58,
        "2023-01-08T04:00:00+01:00"
      ],
      [
        9.92,
        "2023-01-08T05:00:00+01:00"
      ],
      [
        9.02,
        "2023-01-08T06:00:00+01:00"
      ],
      [
        16.469999,
        "2023-01-08T07:00:00+01:00"
      ],
      [
        27.08,
        "2023-01-08T08:00:00+01:00"
      ],
      [
        29.08,
        "2023-01-08T09:00:00+01:00"
      ],
      [
        35.220001,
        "2023-01-08T10:00:00+01:00"
      ],
      [
        70.190002,
        "2023-01-08T11:00:00+01:00"
      ],
      [
        49.080002,
        "2023-01-08T12:00:00+01:00"
      ],
      [
        65.129997,
        "2023-01-08T13:00:00+01:00"
      ],
      [
        62.189999,
        "2023-01-08T14:00:00+01:00"
      ],
      [
        63.490002,
        "2023-01-08T15:00:00+01:00"
      ],
      [
        86.290001,
        "2023-01-08T16:00:00+01:00"
      ],
      [
        118.040001,
        "2023-01-08T17:00:00+01:00"
      ],
      [
        122.610001,
        "2023-01-08T18:00:00+01:00"
      ],
      [
        65.620003,
        "2023-01-08T19:00:00+01:00"
      ],
      [
        60.98,
        "2023-01-08T20:00:00+01:00"
      ],
      [
        60.310001,
        "2023-01-08T21:00:00+01:00"
      ],
      [
        69.400002,
        "2023-01-08T22:00:00+01:00"
      ],
      [
        48.889999,
        "2023-01-08T23:00:00+01:00"
      ]
    ],
    "tomorrow": [
      [
        75.129997,
        "2023-01-09T00:00:00+01:00"
      ],
      [
        64.379997,
        "2023-01-09T01:00:00+01:00"
      ],
      [
        60.279999,
        "2023-01-09T02:00:00+01:00"
      ],
      [
        39.41,
        "2023-01-09T03:00:00+01:00"
      ],
      [
        47.34,
        "2023-01-09T04:00:00+01:00"
      ],
      [
        68.989998,
        "2023-01-09T05:00:00+01:00"
      ],
      [
        107.129997,
        "2023-01-09T06:00:00+01:00"
      ],
      [
        160.0,
        "2023-01-09T07:00:00+01:00"
      ],
      [
        180.0,
        "2023-01-09T08:00:00+01:00"
      ],
      [
        177.139999,
        "2023-01-09T09:00:00+01:00"
      ],
      [
        159.070007,
        "2023-01-09T10:00:00+01:00"
      ],
      [
        160.570007,
        "2023-01-09T11:00:00+01:00"
      ],
      [
        140.559998,
        "2023-01-09T12:00:00+01:00"
      ],
      [
        137.669998,
        "2023-01-09T13:00:00+01:00"
      ],
      [
        143.570007,
        "2023-01-09T14:00:00+01:00"
      ],
      [
        151.020004,
        "2023-01-09T15:00:00+01:00"
      ],
      [
        161.960007,
        "2023-01-09T16:00:00+01:00"
      ],
      [
        174.339996,
        "2023-01-09T17:00:00+01:00"
      ],
      [
        182.179993,
        "2023-01-09T18:00:00+01:00"
      ],
      [
        157.699997,
        "2023-01-09T19:00:00+01:00"
      ],
      [
        145.070007,
        "2023-01-09T20:00:00+01:00"
      ],
      [
        134.619995,
        "2023-01-09T21:00:00+01:00"
      ],
      [
        83.839996,
        "2023-01-09T22:00:00+01:00"
      ],
      [
        80.589996,
        "2023-01-09T23:00:00+01:00"
      ]
    ],
    "tomorrow_calculated": false,
    "api_tomorrow": [
      [
        75.129997,
        "2023-01-09T00:00:00+01:00"
      ],
      [
        64.379997,
        "2023-01-09T01:00:00+01:00"
      ],
      [
        60.279999,
        "2023-01-09T02:00:00+01:00"
      ],
      [
        39.41,
        "2023-01-09T03:00:00+01:00"
      ],
      [
        47.34,
        "2023-01-09T04:00:00+01:00"
      ],
      [
        68.989998,
        "2023-01-09T05:00:00+01:00"
      ],
      [
        107.129997,
        "2023-01-09T06:00:00+01:00"
      ],
      [
        160.0,
        "2023-01-09T07:00:00+01:00"
      ],
      [
        180.0,
        "2023-01-09T08:00:00+01:00"
      ],
      [
        177.139999,
        "2023-01-09T09:00:00+01:00"
      ],
      [
        159.070007,
        "2023-01-09T10:00:00+01:00"
      ],
      [
        160.570007,
        "2023-01-09T11:00:00+01:00"
      ],
      [
        140.559998,
        "2023-01-09T12:00:00+01:00"
      ],
      [
        137.669998,
        "2023-01-09T13:00:00+01:00"
      ],
      [
        143.570007,
        "2023-01-09T14:00:00+01:00"
      ],
      [
        151.020004,
        "2023-01-09T15:00:00+01:00"
      ],
      [
        161.960007,
        "2023-01-09T16:00:00+01:00"
      ],
      [
        174.339996,
        "2023-01-09T17:00:00+01:00"
      ],
      [
        182.179993,
        "2023-01-09T18:00:00+01:00"
      ],
      [
        157.699997,
        "2023-01-09T19:00:00+01:00"
      ],
      [
        145.070007,
        "2023-01-09T20:00:00+01:00"
      ],
      [
        134.619995,
        "2023-01-09T21:00:00+01:00"
      ],
      [
        83.839996,
        "2023-01-09T22:00:00+01:00"
      ],
      [
        80.589996,
        "2023-01-09T23:00:00+01:00"
      ]
    ],
    "predictions": null,
    "api_predictions": null,
    "tariff_data": {
      "additional_tariffs": {
        "transmissions_net_tarif": 0.058,
        "system_tarif": 0.054,
        "el_afgift": 0.008
      },
      "tariffs": {}
    },
    "next_update": "13:38:33",
    "data_source": "Energi Data Service",
    "home_assistant_tz": "Europe/Copenhagen",
    "home_assistant_currency": "DKK"
  }
}

**Comment by MTrab** [comment]
@Coolltazz - det er ikke samme fejl.

**Comment by Coolltazz** [comment]
så opretter jeg lige en ny bug

**Comment by MTrab** [comment]
This is a tough one - seems like N1 isn't publishing data via the API.
I need to investigate this further, so do not expect N1 to be working in the upcoming bugfix later today.

**Comment by HellGreen** [comment]
Can confirm "N1" has an issue.

Additional info: "Trefor El-net A/S" created the the same issue for me. To verify, I then switched to Cerius which works.

**Comment by MTrab** [comment]
> Additional info: "Trefor El-net A/S" created the the same issue for me.

TREFOR was not the same and is fixed in 1.0.1

**Comment by Jellybabz** [comment]
Jeg oplever også fejl endnu ved N1.

**Comment by dartfrogdk** [comment]
det er ikke kun N1 flere af dem giver samme fejl, men kan bekæfte at Cerius virker

**Comment by MTrab** [comment]
Det er muligt der er flere der giver fejl som denne.
De fleste virker heldigvis

**Comment by hostrup** [comment]
Hejsa! 
Kan bekræfte at N1 også fejler hos mig. Nåede dog at lave en defect inden jeg fandt denne... :)

**Comment by MTrab** [comment]
N1 is non-functional at all users, unfortunately.
Working on some tests on how to do the lookup smarter.

**Comment by pvprodk** [comment]
Until its fixed, in the mean time you can use the following additional costs (Based on N1 and Vindstød)

{% set costs = {"elafgift": 0.008,"nettarif_lav": 0.4322,"nettarif_spids": 1.0562,"tariffer_energinet": 0.112,"eltillaeg_ellev": 0.005,"abonnement_ellev": 0.0} %}{% if now().month >= 10 or now().month < 4 %}{% if now().hour >= 17 and now().hour < 20 %} {{costs.elafgift +costs.nettarif_spids +costs.tariffer_energinet +costs.eltillaeg_ellev +costs.abonnement_ellev }}{% else %} {{costs.elafgift +costs.nettarif_lav +costs.tariffer_energinet +costs.eltillaeg_ellev +costs.abonnement_ellev }}{% endif %} {% else %} {{costs.elafgift +costs.nettarif_lav +costs.tariffer_energinet +costs.eltillaeg_ellev +costs.abonnement_ellev }} {% endif %}

**Comment by candstand** [comment]
> {% set costs = {"elafgift": 0.008,"nettarif_lav": 0.4322,"nettarif_spids": 1.0562,"tariffer_energinet": 0.112,"eltillaeg_ellev": 0.005,"abonnement_ellev": 0.0} %}{% if now().month >= 10 or now().month < 4 %}{% if now().hour >= 17 and now().hour < 20 %} {{costs.elafgift +costs.nettarif_spids +costs.tariffer_energinet +costs.eltillaeg_ellev +costs.abonnement_ellev }}{% else %} {{costs.elafgift +costs.nettarif_lav +costs.tariffer_energinet +costs.eltillaeg_ellev +costs.abonnement_ellev }}{% endif %} {% else %} {{costs.elafgift +costs.nettarif_lav +costs.tariffer_energinet +costs.eltillaeg_ellev +costs.abonnement_ellev }} {% endif %}

Sorry, if this is obvious. I olso have n1 and Vindstød, where do i write this code? In the Lovelace card code? or?

**Comment by andcor** [comment]
In the template field in the integration configuration, first page, bottom.
