### ISSUE TITLE
Template for deduction of fees above a certain usage

### ISSUE THREAD

**Issue by 3liasen** [MTrab/energidataservice#179]
It would be an excellent feature, if it's possible to implement e.g. a tick box, stating that there's a deduction in costs due to reduced costs when consumption is over 4000 kWh per year.

**Comment by MTrab** [comment]
This needs to be in a template - it's nearly impossible to make this smart in any other ways.

**Comment by woopstar** [comment]
If you have a sensor that counts the amount of power users per month, you can use this template with version 1.2.3

````
{% if states("sensor.hovedforsyning_energy_total_current_month") | float > 334 and now().month > 6 %}
  {% set reduction = ( el_afgift - 0.008 ) | float(0) %}
{% endif %}

{{ 0.012 - reduction|default(0) | float(0) }}
```

**Comment by 3liasen** [comment]
Thanks, Andreas. Right now I'm using the template example from the Wiki {{0.03544|float}}, and coincidentally I'm using Norlys FlexEl as well, so it works fine.

 If I understand this right, I should be able to use your template (which this second is also available after @MTrab has updated her Wiki). Already updated to v1.2.3
 
 Thank you both!!! No more 200 line templates for me. ;-)

**Comment by MTrab** [comment]
Fixed by #261 and a great bit of help in #259 (Thanks @woopstar )

**Comment by DK-MGO** [comment]
Hello,

Would it be possible for someone to write a small how-to for combining:
- https://github.com/MTrab/energidataservice/wiki/How-to-add-costs-of-subscription-and-delivery%3F#additional-costs-template-when-using-tariff-data
and
- https://github.com/MTrab/energidataservice/wiki/Template-example-for-using-reduced-electrical-fee-in-Denmark,-using-over-4000kWh-pr.-year

I guess the first is entered into the setup UI for Energi Data Service, but then how do I use the second?

Thank you!

**Comment by woopstar** [comment]
> Hello,
> 
> Would it be possible for someone to write a small how-to for combining:
> 
> * https://github.com/MTrab/energidataservice/wiki/How-to-add-costs-of-subscription-and-delivery%3F#additional-costs-template-when-using-tariff-data
>   and
> * https://github.com/MTrab/energidataservice/wiki/Template-example-for-using-reduced-electrical-fee-in-Denmark,-using-over-4000kWh-pr.-year
> 
> I guess the first is entered into the setup UI for Energi Data Service, but then how do I use the second?
> 
> Thank you!

Just change the pricing in the last URL to match the price from first URL in this part:

```
{{ 0.012 - reduction | default(0) | float(0) }}
```

The 0.012 equals Vindstød VEStrøm

**Comment by DK-MGO** [comment]
Thank you for the swift reply, and pardon if I am a bit slow...

But I update the template from the first URL to fit with my electricity provider:
`{% set costs = {
    "elafgift": 0.763,
    "nettarif_lav": 0.1636,
    "nettarif_spids": 0.4537,
    "abonnement_net": 0.09425,
    "eltillaeg_ellev": 0.07,
    "abonnement_ellev": 0.725
    } %}

{% if now().month >= 10 or now().month < 4 %}
  {% if now().hour >= 17 and now().hour < 20 %}
{{
  costs.elafgift + 
  costs.nettarif_spids + 
  costs.abonnement_net + 
  costs.eltillaeg_ellev + 
  costs.abonnement_ellev
}}
  {% else %}
{{
  costs.elafgift + 
  costs.nettarif_lav + 
  costs.abonnement_net + 
  costs.eltillaeg_ellev + 
  costs.abonnement_ellev
}}
  {% endif %}
{% else %}
{{
  costs.elafgift + 
  costs.nettarif_lav + 
  costs.abonnement_net + 
  costs.eltillaeg_ellev + 
  costs.abonnement_ellev
}}
{% endif %}`


and paste that in here:
![image](https://github.com/MTrab/energidataservice/assets/101643418/ad472f8a-fae8-4754-a866-57184e7ceba0)


But what do I do with this?
`{{ 0.012 - reduction | default(0) | float(0) }}`


or more specifically with this:
`{% if states("sensor.hovedforsyning_energy_total_current_month") | float > 334 %}   
  {% set reduction = ( el_afgift - 0.008 ) | float(0) %}
{% endif %}

{{ 0.012 - reduction | default(0) | float(0) }}`
