### ISSUE TITLE
Elinord is also missing as net operator

### ISSUE THREAD

**Issue by MTrab** [MTrab/energidataservice#180]
Elinord is also missing as net operator

_Originally posted by @Sdahl1234 in https://github.com/MTrab/energidataservice/issues/177#issuecomment-1374815523_

**Comment by MTrab** [comment]
Which region does Elinord cover?

**Comment by Sdahl1234** [comment]
Elinord leverer el til private husstande og virksomheder i Sæby, Strandby, Frederikshavn by, det meste af Elling og oplandet i dette område.

From elinord.dk
