### ISSUE TITLE
[FR]: Ability to find sell prices (by deducting production fees) or get the raw prices (by not adding consumer fees)

### ISSUE THREAD

**Issue by bjornbak** [MTrab/energidataservice#185]
**Is your feature request related to a problem? Please describe.**
The new version 1.0.0 feature of automatically adding the consumer fees is fantastic so we don't have to maintain a additional_costs template but with solar panels I need to know both the buy prices and the sell prices.

Where buy prices are the exchange prices plus the hour's consumer fees sell prices are the exchange prices minus production fees.

The naive approach would be to deduct both the consumer and production fees from the integration's calculated prices to find the sell prices but it kind of ruins the idea in new feature :(

Until now I have been running two installations of the integration with different additional_costs templates for consumer fees and productions fees (production fees being negative).

**Describe the solution you'd like**
It would of course be fantastic to be able to run the integration in "sell" mode and get the sell prices calculated automatically.

**Describe alternatives you've considered**
I understand that is might be too special a need so I'll settle with an option to turn off the automatic addition of consumer fees so I get the raw exchange price (with or without VAT).

**Additional context**

**Comment by MTrab** [comment]
For now, this will require a template, and I think it'll be a difficult task to include into the integration.

**Comment by bjornbak** [comment]
Is the alternative solution of NOT adding the fees calculated in the integration but only those in the additional_costs template difficult too?
Aka the old school behavior.

**Comment by MTrab** [comment]
No change to that - just leave the tariff option off

**Comment by bjornbak** [comment]
I missed that option in the show case screenshots shared on FB and didn't dare to upgrade...
But with this option I got what I **need**.
Let me close this ticket.
Thank you for a great integration!!
