### ISSUE TITLE
Error adding entities for domain sensor with platform energidataservice

### ISSUE THREAD

**Issue by ChecksumDK** [MTrab/energidataservice#186]
### Environment:
- Home Assistant version: 2023.1.1
- Energidatastyrelsen version: 1.0.1
- Operation system: Home Assistant OS 9.4

## Configuration
- Country: Denmark
- Region: West of the great belt
- Show prices incl. VAT: yes
- Show in cents: No
- Number of decimals 2
- Price calculated in: kWh
- AI Forecast from carnot: yes
- Automatically fetch tariff data: yes
- Net operator: FLOW Elnet A/S

## Additional cost template
{{0.0|float}}

## Describe the bug
The integration did deliver data for a short time, but then it stopped. In the system log I get the following error:
- Error adding entities for domain sensor with platform energidataservice
- Error while setting up energidataservice platform for sensor

The integration works fine if I disable the awesome "Automatically fetch tariff data"

## Debug log
[DebugLog.txt](https://github.com/MTrab/energidataservice/files/10369377/DebugLog.txt)
[LogDetails.txt](https://github.com/MTrab/energidataservice/files/10369365/LogDetails.txt) 

## Diagnostic
[DiagnosticLog.txt](https://github.com/MTrab/energidataservice/files/10369386/DiagnosticLog.txt)

**Comment by andcor** [comment]
I get this exact error when I try running the integration with the automatical fetching of tariff data. If I turn it off, the integration loads just fine. My net operator is N1 A/S, but I have tried with several different operators. I have also tried to remove the integration and then make a new one, but this doesn't work either.

I have tried editing the code to get the content of the tariff_data just before the error occurs by adding this line to the code:
_LOGGER.warning("tariff_data:\n%s", json.dumps(self._api.tariff_data["tariffs"], indent=2, default=str)) at line 582 of sensor.py. This gives me this output in the log:
tariff_data: { "0": 0.2235, "1": null, "2": null, "3": null, "4": null, "5": null, "6": null, "7": null, "8": null, "9": null, "10": null, "11": null, "12": null, "13": null, "14": null, "15": null, "16": null, "17": null, "18": null, "19": null, "20": null, "21": null, "22": null, "23": null }

**Comment by MTrab** [comment]
> I get this exact error when I try running the integration with the automatical fetching of tariff data. If I turn it off, the integration loads just fine. My net operator is N1 A/S, but I have tried with several different operators. I have also tried to remove the integration and then make a new one, but this doesn't work either.
> 
> I have tried editing the code to get the content of the tariff_data just before the error occurs by adding this line to the code: _LOGGER.warning("tariff_data:\n%s", json.dumps(self._api.tariff_data["tariffs"], indent=2, default=str)) at line 582 of sensor.py. This gives me this output in the log: tariff_data: { "0": 0.2235, "1": null, "2": null, "3": null, "4": null, "5": null, "6": null, "7": null, "8": null, "9": null, "10": null, "11": null, "12": null, "13": null, "14": null, "15": null, "16": null, "17": null, "18": null, "19": null, "20": null, "21": null, "22": null, "23": null }

NOT same error - and for N1: https://github.com/MTrab/energidataservice/issues/178

**Comment by ChecksumDK** [comment]
Deleted the integration. Restarted HA. Reinstalled the integration and now it works. 
Instead of using the entity name "el-priser" I used "elpriser" this time. I do not know if that makes a difference?

[config_entry-energidataservice-a1ee208cb52979d36350e47b4167616f.json.txt](https://github.com/MTrab/energidataservice/files/10371365/config_entry-energidataservice-a1ee208cb52979d36350e47b4167616f.json.txt)
