### ISSUE TITLE
[FR]: Expose tariffs as attributes

### ISSUE THREAD

**Issue by cnrd** [MTrab/energidataservice#187]
Would it be possible to expose the new tariffs as attributes of the same format as prices? They should of course still be included in the prices, but it would be nice to have the data available.

**Comment by bluefuzz** [comment]
Yes, it would be nice to see the actual tariff numbers somewhere. I see a small discrepancy (about 7 øre/kWh) between my own numbers and what EDS is getting which I can't quite account for ...

**Comment by ujhede** [comment]
> Yes, it would be nice to see the actual tariff numbers somewhere. I see a small discrepancy (about 7 øre/kWh) between my own numbers and what EDS is getting which I can't quite account for ...

Did you factor in the elnet contribution ?  In Radiusnet land it is about 0.11229 DKK/kWh.  Not sure if it is the same with all net distributors.

**Comment by ujhede** [comment]
Please also add the tariffs to as sub attributes to the "raw" attributes.

**Comment by MTrab** [comment]
> Please also add the tariffs to as sub attributes to the "raw" attributes.

? I don't think I understand?

**Comment by MTrab** [comment]
Tariffs as attributes, like the today, tomorrow and forecast attributes, are planned - stay tuned ;)
Other issues have priority, but this will be implemented in near future.

**Comment by MTrab** [comment]
> Yes, it would be nice to see the actual tariff numbers somewhere. I see a small discrepancy (about 7 øre/kWh) between my own numbers and what EDS is getting which I can't quite account for ...

Did you compare to elspotpris.dk and added the extra fees for your electrical company as mentioned in the releasenotes?

**Comment by bluefuzz** [comment]
> Did you factor in the elnet contribution ? In Radiusnet land it is about 0.11229 DKK/kWh. Not sure if it is the same with all net distributors.

Yes, but I found I was using the wrong numbers. I was using the following table copied from [this page](https://energinet.dk/El/Elmarkedet/Tariffer/Aktuelle-tariffer/) at energinet only last week! But the table is gone now and the numbers are different. They were stated as being prices without moms ...

![image](https://user-images.githubusercontent.com/5837578/211498937-ff420ae0-42c5-475a-9042-cfc4d8ef1730.png)

**Comment by ujhede** [comment]
> > Please also add the tariffs to as sub attributes to the "raw" attributes.
> 
> ? I don't think I understand?

The sensor raw attributes have the price including tariffs for each hour today and tomorrow.  What I would like is to also have the tariff available for each hour.  Maybe even the individual tariff components.

**Comment by MTrab** [comment]
Okay - wasn't sure that was what you had in mind - but that is just about what I have planned for the attributes ;)
