### ISSUE TITLE
Clarification of the new automatic tariffs

### ISSUE THREAD

**Issue by cnrd** [MTrab/energidataservice#188]
Does the new tariff feature only fetch the net operator tariffs and not taxes or other fees? (I guess yes), so that we still need to manually add taxes and so on to the additional costs?

Thanks!

**Comment by MTrab** [comment]
The ONLY change is that net operators tariffs are added automatically - EVERYTHING else is as before.

**Comment by cnrd** [comment]
Great, thanks 👍
