### ISSUE TITLE
[FR]: Autofind charge owner from Home Assistant coordinates

### ISSUE THREAD

**Issue by MTrab** [MTrab/energidataservice#204]
It would be AWESOME if the tariff connector could find the correct charge owner (net operator) from the coordinates in the Home Assistant settings, and then preselect the charge owner in the combobox.

**Comment by AMajland** [comment]
My guess is that there will be many edge cases arround the smaller nets where it will select the wrong one just from a coordinate

For it to work my guess is that is has to be a lookup on the address like https://greenpowerdenmark.dk/vejledning-teknik/nettilslutning/find-netselskab 

Just look at the shape of the border for Energi Viborg 
![image](https://user-images.githubusercontent.com/97510471/212008759-0d208213-3bc5-4c2b-81cd-385453061ffb.png)

**Comment by MTrab** [comment]
This is ONLY for my own planning and NOT ment as a discussion yet.
