### ISSUE TITLE
Add Vindstød A/S as Operator

### ISSUE THREAD

**Issue by jesperuc** [MTrab/energidataservice#211]
Vindstød A/S is missing as  Operator 

I can't seem to find their prices on their website. 
I'll be happy to share an invoice from vindstød where all prices are visible. 
Please reach out if necessary

**Comment by MTrab** [comment]
Vindstød is NOT an operator.
Vindstød is the supplier so to speak, but not the cable/net operator.

**Comment by MTrab** [comment]
You can lookup your net operator in this page: https://greenpowerdenmark.dk/vejledning-teknik/nettilslutning/find-netselskab

Will be added to the README/Wiki later, just haven't had the time yet.
