### ISSUE TITLE
 No module named 'currency_converter'

### ISSUE THREAD

**Issue by PocketPi** [MTrab/energidataservice#213]
### Environment:
- Home Assistant version: Home Assistant 2023.1.4
- Energidatastyrelsen version: 1.1.0
- Operation system: Alpine Linux 5.15.80-0-lts
- Home Assistant run in docker

## Describe the bug
I am trying to get Energy Data Service to work but when I try to add the integration I get the following error: 

2023-01-13 17:46:56.723 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration energidataservice: No module named 'currency_converter'

**Comment by PocketPi** [comment]
Installing pip and after that CurrencyConverter solved the problem. 

Might be nice stuff for the wiki :)

**Comment by MTrab** [comment]
If you haven't had PIP installed before, you'd have other problems.
Sounds to me like you haven't had a fully supported setup.
This is not for the wiki of this integration, as I take that the installations are supported.
