### ISSUE TITLE
no net operators shown

### ISSUE THREAD

**Issue by ewonais** [MTrab/energidataservice#214]
i am in se3
tested fi, fr and de
![image](https://user-images.githubusercontent.com/86527854/212390474-d98425bc-eb7b-4cec-b244-18d8752f21ff.png)

**Comment by MTrab** [comment]
Currently we only support Danish net operators, as I have no knowledge of API endpoints for other countries.

In a later version the possibility to enable the tariff connector will be disabled for invalid regions
