### ISSUE TITLE
Ravdex missing after update

### ISSUE THREAD

**Issue by koburg** [MTrab/energidataservice#216]
ravdex is missing after latest update.

**Comment by MTrab** [comment]
Ravdex being?

**Comment by koburg** [comment]
el net leverandør

**Comment by MTrab** [comment]
For which area?

**Comment by koburg** [comment]
This Net Leverandør was in the Last version of this integration therefore I assumed you knew it.

[https://ravdex.dk](url)
belong to FYN/Kerteminde Kommune

**Comment by MTrab** [comment]
Fixed in next release
