### ISSUE TITLE
How do i remove  {% set costs = {     "elafgift": 0.00, ... 

### ISSUE THREAD

**Issue by pemca** [MTrab/energidataservice#237]
After the fixed prices per Net Company is implemented, i want to remove the old calculation.  {% set costs = {     "elafgift": 0.00, ...
If i go to configuration and delete the string it is still there after save. How can i remove it without reinstall integration ?
Thanks, Peter Calum

**Comment by MTrab** [comment]
See the existing issue: https://github.com/MTrab/energidataservice/issues/174
