### ISSUE TITLE
[Q]: "Next data update" attribute

### ISSUE THREAD

**Issue by mm98** [MTrab/energidataservice#239]
This isn't really a issue but more of a question :)

I've noticed, that the sensor attribute `Next data update` only moves forward. For me, it never changes to anything earlier. It has been `13:30:34` for some days and now it moved to `13:32:52` (never before 13:30). Or is this just an coincident by me?

When I look at the code, it should be random (between 5 and 40 mins past 1PM).

https://github.com/MTrab/energidataservice/blob/a6baf6de6e77e0cdab3c1323e6a30bf2801ffac3/custom_components/energidataservice/__init__.py#L38-L39

https://github.com/MTrab/energidataservice/blob/a6baf6de6e77e0cdab3c1323e6a30bf2801ffac3/custom_components/energidataservice/__init__.py#L367-L370

**Comment by MTrab** [comment]
The number is random generated when loading the integration
