### ISSUE TITLE
Missing provider

### ISSUE THREAD

**Issue by Ralleberg** [MTrab/energidataservice#240]
The supplier "Energy Fyn" is missing from the list of providers.

**Comment by MTrab** [comment]
I cannot find any operators on Fyn by that name.

Is this a subscription company and not an operator?
Is it available from elspotpris.dk?

**Comment by MTrab** [comment]
Energi Fyn is not a net operator but a supplier and is present in the supplier list here: https://github.com/MTrab/energidataservice/wiki/How-to-add-costs-of-subscription-and-delivery%3F#additional-costs-template-when-using-tariff-data
