### ISSUE TITLE
Error in filter for Elektrus: Wrong GLN

### ISSUE THREAD

**Issue by jlaur** [MTrab/energidataservice#242]
I found this repository when working on a similar integration in openHAB: openhab/openhab-addons#14222

Looking at your code helped me in the right direction of providing customized filters for the different grid companies.

I believe I found a small problem here:
https://github.com/MTrab/energidataservice/blob/44caf31a54ef3b2ec04d2d9dd690deb047f6512c/custom_components/energidataservice/tariffs/energidataservice/chargeowners.py#L52-L63

These two filters refer to the same GLN. The one for TREFOR El-net Øst seems to be the correct one, since the other one didn't give any results. But doing a broad cross-GLN search, I found the GLN for Elektrus to be 5790000836239. This was confirmed by seeing charge type code 6000091 in this dataset, which is also in your filter:
https://api.energidataservice.dk/dataset/DatahubPricelist?filter={%22GLN_Number%22:[%225790000836239%22],%22ChargeType%22:[%22D03%22],%22ChargeTypeCode%22:[%226000091%22],%22Note%22:[%22Nettarif%20C%20time%22]}&columns=ValidFrom,ValidTo,GLN_Number,ChargeOwner,ChargeTypeCode,Note&start=2023-01-01

Btw, the compiler found the problem for me because of duplicate values in a switch/case:
https://github.com/jlaur/openhab-addons/blob/14222-energidataservice/bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/DatahubTariffFilterFactory.java

Out of curiosity, are the filters used here provided/reported by users, or which workflow do you use for updating them?

**Comment by MTrab** [comment]
Good find - sometimes it just goes too fast ;) I'll fix this for the next release.

As for the filters, charge owners, it's currently manually as there are so many combinations of type and notes, that I haven't made that automated yet.
