### ISSUE TITLE
TypeError: 'datetime.datetime' object is not callable

### ISSUE THREAD

**Issue by woopstar** [MTrab/energidataservice#259]
The latest release v1.2.2 gives me this issue. I think it's because of the template used.

```
  File "/config/custom_components/energidataservice/sensor.py", line 619, in _calculate
    template_value = self._cost_template.async_render(
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 459, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TypeError: 'datetime.datetime' object is not callable
```

Template:
```
{% set costs = {   
    "nettarif_c_time_sommer_lav": 0.1212,   
    "nettarif_c_time_sommer_hoj": 0.1818,   
    "nettarif_c_time_sommer_spids": 0.4726,   
    "nettarif_c_time_vinter_lav": 0.1212,   
    "nettarif_c_time_vinter_hoj": 0.3635,   
    "nettarif_c_time_vinter_spids": 1.0905,   
    "abonnement_net": 0.046,   
    "spotpris_tillaeg": 0.012,   
    "transmission_nettarif": 0.05800,   
    "systemtarif": 0.05400,   
    "abonnement_el_leverandor": 0, 
} %}  

{% if states("sensor.hovedforsyning_energy_total_current_month") | float < 336 %}   
    {% if now().month >= 1 and now().month < 7 %}     {% set elafgift = 0.008 %}   {% else %}     {% set elafgift = 0.680 %}   {% endif %} {% else %}   {% set elafgift = 0.008  %} {% endif %}  {% set sum_price = costs.transmission_nettarif +        costs.spotpris_tillaeg +        costs.systemtarif +         elafgift +        costs.abonnement_net +        costs.abonnement_el_leverandor  %}  {% if now().month >= 10 or now().month < 4 %}   {% if now().hour >= 0 and now().hour < 6 %}     {{ sum_price + costs.nettarif_c_time_vinter_lav }}   {% endif %}   {% if now().hour >= 6 and now().hour < 17 %}     {{ sum_price + costs.nettarif_c_time_vinter_hoj }}   {% endif %}   {% if now().hour >= 17 and now().hour < 21 %}     {{ sum_price + costs.nettarif_c_time_vinter_spids }}   {% endif %}   {% if now().hour >= 21 and now().hour <= 23 %}     {{ sum_price + costs.nettarif_c_time_vinter_hoj }}   {% endif %} {% else %}   {% if now().hour >= 0 and now().hour < 6 %}     {{ sum_price + costs.nettarif_c_time_sommer_lav }}   {% endif %}   {% if now().hour >= 6 and now().hour < 17 %}     {{ sum_price + costs.nettarif_c_time_sommer_hoj }}   {% endif %}   {% if now().hour >= 17 and now().hour < 21 %}     {{ sum_price + costs.nettarif_c_time_sommer_spids }}   {% endif %}   {% if now().hour >= 21 and now().hour <= 23 %}     {{ sum_price + costs.nettarif_c_time_sommer_hoj }}   {% endif %} {% endif %}
```

The template works in Developer Tools.

**Comment by MTrab** [comment]
There was some changes in the templates I had to make.
Could you please try removing () after your now vars? Perhaps that could be the issue.

**Comment by woopstar** [comment]
Removing () in now vars throws this error:

<img width="567" alt="image" src="https://user-images.githubusercontent.com/2997782/218040056-bb6731aa-d543-4703-a5e9-0670866e1d6f.png">

Throwing it into developer tools gives this error, as expected:

<img width="516" alt="image" src="https://user-images.githubusercontent.com/2997782/218040275-9ff45319-83b5-4223-b507-5f7ca4c13e6f.png">

**Comment by MTrab** [comment]
Okay - will look into this.

You are aware that you can just enable automatic tariff data, right?

**Comment by woopstar** [comment]
Yes. It's super nice, but it does not work for me after 1/7 when the energy charge changes again. I have a heat pump and hence reduced energy charge prices. So I need to calculate that the price changes every month when I have consumed 334 kWh.

**Comment by MTrab** [comment]
No need to miss out on auto tariffs just for that.

You have the tariff sum as a variable in the templates.

**Comment by woopstar** [comment]
> No need to miss out on auto tariffs just for that.

You are right. So with Vindstød VE Strøm, and looking into https://fm.dk/media/26367/faktaark_lempelse-af-elafgift-til-minimumssats-i-seks-maaneder.pdf

The template should look like this:

```
{% if states("sensor.hovedforsyning_energy_total_current_month") | float > 336 and now().month > 6 %}   
  {% set elafgift_reduction = (69.7 * 0.8 - 0.8 * 0.8) | float %}
{% endif %}

{{ 0.012 - elafgift_reduction|default(0) | float(0) }}
 ```
 
 So it subtracts the diff between the regular energy price of 69.7 incl VAT and the reduced one incl VAT.
 
 I multiply with 0.8 to remove VAT as I believe you add VAT automatically ?

**Comment by MTrab** [comment]
Don't know what the 69.7 you have is, but yes - all prices in the template is VITHOUT VAT, as the integration calculates this automatically based on your settings.

**Comment by woopstar** [comment]
According to FM, the energy price will be 69,7 øre kr/kWh in H2 2023. But ofc, it's øre, so the above needs to be reduced by 100 :D

**Comment by MTrab** [comment]
` 0.008 * 0.8` ??

Shouldn't it just be 0.008?
Perhaps I should just add the elafgift as a variable as well if auto tariff is enabled, then you can just use this variable

**Comment by MTrab** [comment]
0.008 is without. Current elafgift is 0.008 without VAT and 0.01 with VAT

**Comment by woopstar** [comment]
Ah. I see. then 0.697 is also without VAT.

Exposing the `elafgift` could work. So you could just override it when you have used more than 336 kWh and set it fixed to 0.008

**Comment by woopstar** [comment]
With #261 would the use case then be like this?

```
{% if states("sensor.hovedforsyning_energy_total_current_month") | float > 336 and now().month > 6 %}   
  {% set el_afgift = 0.008 %}
{% endif %}
{{ 0.012 | float(0) }}
```

**Comment by MTrab** [comment]
More like this - without having done any tests to confirm yet
```
{% set reduction = 0
{% if states("sensor.hovedforsyning_energy_total_current_month") | float > 336 and now().month > 6 %}   
  {% reduction = 0.008 %}
{% endif %}
{{ 0.012 - reduction | float(0) }}
```

It's not possible to send variable changes back from templates, as far as I can see.

**Comment by woopstar** [comment]
I'm pretty sure if you do not do anything in your template, the calculated price will be using the regular charged price of `0.697`, but with reduced charge pricing due to heat pumps, you'd want to reduce it to `0.008` when you have consumed `334 kWh` during the month. Current rules are that you get reduced charge prices when you have consumed 4.000 kWh a year, which is normally divided into the months hence `4.000 / 12 = 334 kWh` in the current month. 

So I believe you must subtract `0.689 (0.697-0.008)` from the current calculated price. This means this should be correct:

```
{% if states("sensor.hovedforsyning_energy_total_current_month") | float > 334 and now().month > 6 %}   
  {% set reduction = ( el_afgift - 0.008 ) | float(0) %}
{% endif %}

{{ 0.012 - reduction|default(0) | float(0) }}
```

This would remove the difference between the current charged price `el_afgift`, which is currently `0.697` in H2 2023, and the reduced pricing of `0.008`

**Comment by MTrab** [comment]
Not into the reduction rules anymore, but you are right - my example reduced by the full amount.

**Comment by woopstar** [comment]
If you release a beta release, I can test it out right away.

Yes, let's add it to the wiki. I think a lot of people could benefit from the example if they monitor their usage and have heat pumps giving them reduced charged prices. But ofc it requires a sensor.

We could also possibly look into that you can provide a sensor entity to EDS during config with the current month's power consumption, and then it auto-calculates.

**Comment by MTrab** [comment]
Just pushed 1.2.3 as a pre-release, please do test and let me know if it works

**Comment by woopstar** [comment]
> Just pushed 1.2.3 as a pre-release, please do test and let me know if it works

I can confirm 1.2.3 works with the regular template again, as mentioned in the issue text.

Also tested with auto tariff and the following template:

```
{% if states("sensor.hovedforsyning_energy_total_current_month") | float > 334 and now().month > 6 %}   
  {% set reduction = ( el_afgift - 0.008 ) | float(0) %}
{% endif %}

{{ 0.012 + (402/365/100) - reduction|default(0) | float(0) }}
```

Also works.

**Comment by woopstar** [comment]
But I just tested this:

I also just tested this template to test the `el_afgift` variable:

```
{% if states("sensor.hovedforsyning_energy_total_current_month") | float > 334 and now().month > 0 %}   
  {% set reduction = ( el_afgift - 20.008 ) | float(0) %}
{% endif %}

{{ 0.012 + (402/365/24/100) - reduction|default(0) | float(0) }}
```

Does not seem to work. It does not seem to affect the pricing.

**Comment by MTrab** [comment]
I'll mark it as a normal release at once and get that template in the wiki - thanks :)

**Comment by MTrab** [comment]
Can you explain this?

```
(402/365/24/100)
```

**Comment by woopstar** [comment]
Ah. Yes.

Vores Elnet which is my provider has a yearly fee of 402 kr ex VAT (abonnement). So I added it to the kW price too in my case to get my total of "what I'm paying to get power".

You should leave it out in the wiki.

**Comment by MTrab** [comment]
So just to confirm - this should be the one for the wiki?

```
{% if states("sensor.hovedforsyning_energy_total_current_month") | float > 334 and now().month > 6 %}   
  {% set reduction = ( el_afgift - 0.008 ) | float(0) %}
{% endif %}

{{ 0.012 - reduction | default(0) | float(0) }}
```

**Comment by MTrab** [comment]
And another thing - isn't the reduction for all the months of the year, and not just for the last 6 months?

**Comment by woopstar** [comment]
> So just to confirm - this should be the one for the wiki?
> 
> ```
> {% if states("sensor.hovedforsyning_energy_total_current_month") | float > 334 and now().month > 6 %}   
>   {% set reduction = ( el_afgift - 0.008 ) | float(0) %}
> {% endif %}
> 
> {{ 0.012 - reduction | default(0) | float(0) }}
> ```

> And another thing - isn't the reduction for all the months of the year, and not just for the last 6 months?

You are right. Which means we could remove `and now().month > 6` from the if clause, because the reduction would just be 0 then, since the current charge price is 0.008.

**Comment by MTrab** [comment]
Right :)

**Comment by MTrab** [comment]
https://github.com/MTrab/energidataservice/wiki/Template-example-for-using-reduced-electrical-fee-in-Denmark,-using-over-4000kWh-pr.-year

**Comment by woopstar** [comment]
Using that template something odd happens. It gives me:

<img width="575" alt="image" src="https://user-images.githubusercontent.com/2997782/218119086-a1aed337-5d1e-4e00-af1d-cfdbe8153a0d.png">


But it works in Developer Tools.

**Comment by woopstar** [comment]
```
2023-02-10 15:38:26.268 ERROR (MainThread) [custom_components.energidataservice.config_flow] UndefinedError: 'el_afgift' is undefined
2023-02-10 15:38:51.340 ERROR (MainThread) [custom_components.energidataservice.config_flow] UndefinedError: 'el_afgift' is undefined
2023-02-10 15:39:54.901 ERROR (MainThread) [custom_components.energidataservice.config_flow] UndefinedError: 'el_afgift' is undefined
```

**Comment by woopstar** [comment]
Oh the variable name is `elafgift` and not `el_afgift`

**Comment by MTrab** [comment]
Need to check to source - that doesn't sound right

**Comment by MTrab** [comment]
Strange - the source dictates el_afgift
![image](https://user-images.githubusercontent.com/14296463/218120595-d1eda5a4-e581-47d9-b4bf-63a5ccd88cc7.png)

**Comment by woopstar** [comment]
It does not like to use it inside the template.

Seems it did not test the `el_afgift` variable because of the month checking ofc. 🗡️ 🦤

**Comment by MTrab** [comment]
I've updated the wiki to reflect the working variable

**Comment by MTrab** [comment]
Nope - but I think I know why ;)

**Comment by woopstar** [comment]
> Should be fixed now - and the correct variable is el_afgift ;)

Yes. Works now.
