### ISSUE TITLE
Issue with tariff data when using 2 or more instances of the integration

### ISSUE THREAD

**Issue by woopstar** [MTrab/energidataservice#265]
When you enable the functionality to auto-fetch tariff prices, it uses an external API to do so.

If a timeout occurs to the API, it causes EDS to have prices without tariff, giving wrong calculations, etc.

I believe we need to implement a retry mechanism with a potential exponential backoff strategy when fetching data, such as here:

https://github.com/MTrab/energidataservice/blob/master/custom_components/energidataservice/tariffs/energidataservice/__init__.py#L71

I experienced today at 13.00 that EDS updated, but tariff was not fetched, causes my EDS instance to only have spot prices and template value as the calculated price. Reloading the plugin caused it to fetch the tariff again and prices was correct once again.

**Comment by AndersV209** [comment]
this might be the same issue i have reported on #241

**Comment by woopstar** [comment]
Still an issue after update with this fix included.

<img width="684" alt="image" src="https://user-images.githubusercontent.com/2997782/218403266-68ee944a-0763-4805-9db1-6c3db5c90cab.png">

**Comment by MTrab** [comment]
Not sure what I'm supposed to see in that picture 🤷🏼‍♀️

**Comment by woopstar** [comment]
Yeah... about that.... was just a copy-paste. I'm still seeing that it does not auto fetches the tariff. But I just went through the logs, and no issues are found. Reloading the plugin corrects the issue.

I'm unsure if the API gives some sort of timeout. Maybe we should add a sensor/attribute of "last fetched auto tariff" to see if it's actually the case. It can also be used for automation to reload/fetch in case of network/API/other errors.

**Comment by MTrab** [comment]
Exactly why I want it, so I can setup an identical test before that ;)
So please share.

**Comment by woopstar** [comment]
> Exactly why I want it, so I can setup an identical test before that ;) So please share.

Anything specific to prepare except to enable debug mode for the plugin at 12.55?

**Comment by MTrab** [comment]
It's the diagnostics - not debug

**Comment by woopstar** [comment]
Today everything worked, so have to wait for tomorrow.

**Comment by MTrab** [comment]
Please please please send the diagnostics BEFORE!
That way we can compare the results.

**Comment by woopstar** [comment]
Todays diagnostics . Downloaded at 13.02.

[config_entry-energidataservice-a8887634391dff8e57ef04b9c67aa351.json (1).txt](https://github.com/MTrab/energidataservice/files/10732229/config_entry-energidataservice-a8887634391dff8e57ef04b9c67aa351.json.1.txt)

**Comment by woopstar** [comment]
Issue happened today again.

With error, diagnostics at 14.14.
[config_entry-energidataservice-a8887634391dff8e57ef04b9c67aa351.json.txt](https://github.com/MTrab/energidataservice/files/10746711/config_entry-energidataservice-a8887634391dff8e57ef04b9c67aa351.json.txt)

Without error after reload of EDS, at 14.16:
[config_entry-energidataservice-a8887634391dff8e57ef04b9c67aa351.json2.txt](https://github.com/MTrab/energidataservice/files/10746716/config_entry-energidataservice-a8887634391dff8e57ef04b9c67aa351.json2.txt)

Picture showing diff for before and after reload:
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/2997782/219134614-ea81bc82-2403-40dd-b218-8a925d245de9.png">

**Comment by MTrab** [comment]
Strange - looking at the diagnostics, the tariffs have been fetched. Must be some calculation error, just can't see what should cause that for you and not me.

Could you perhaps try running for some days without the reduction calculation, just to see if that is what make the difference

**Comment by woopstar** [comment]
Had the same issue again today. Will try to remove the cost reduction to see if that mitigates the issue.

One note is: I have two instances of EDS running. Could it be some race condition?

**Comment by MTrab** [comment]
Could be. I wasn't aware of that. I only use one instance

**Comment by MTrab** [comment]
Okay - with 2 instances I see the same issue.

**Comment by woopstar** [comment]
Ah.. So we found the issue, and it's related to multi instance. That's nice.

Most likely a race condition or a singleton/instance thingy.

**Comment by MTrab** [comment]
Fix should be up shortly - think I found the bug. Had forgotten a unique update-tag, so one instance forced data update on both, and if both wasn't fully ready it would result in invalid data in one or both instances.
