### ISSUE TITLE
Tarif er forskudt ved midnat

### ISSUE THREAD

**Issue by BFipsen** [MTrab/energidataservice#267]
- Home Assistant version: 2023.2.1
- Energidatastyrelsen version: 1.2.5
- Operation system: HAOS 9.5

- Country: Denmark
- Region: West of the great belt
- Show in cents: No
- Number of decimals 3
- Trefor forsyning

## Describe the bug
Taraif er forskudt 1 time ved midnat, men kun ved fastpris.
![Screenshot_20230217-121926](https://user-images.githubusercontent.com/47211841/219649925-fde90287-f3b2-439e-94b5-016cf6f1c5f3.jpg)

**Comment by MTrab** [comment]
Please create an issue with all the required information
