### ISSUE TITLE
Feature request:  Current tarif name attribute 

### ISSUE THREAD

**Issue by ujhede** [MTrab/energidataservice#274]
I have some automations that I would like to control using the current transport tarif. (Low, High and Peak where I live).

I know you publish tarif values per hour and naturally I can use those, but that requires some relatiely complex templating to figure out if the current hours values is the highest, lowest or middel one.

So it would be very useful if you could publish the current tarif name (or whatever identifier EDS provides) as an attribute.

Thanks sp much for spending time on this crazy useful integration.

**Comment by MTrab** [comment]
The tariffs have no name in the API, It's presented as you see in this integration.
