### ISSUE TITLE
Unit on elpris causes logging to fail 

### ISSUE THREAD

**Issue by ChecksumDK** [MTrab/energidataservice#286]
![image](https://user-images.githubusercontent.com/43034297/227809372-234c0031-879c-4d23-9d99-29f49f6b93a0.png)
The statistics unit "DKK/KWh" is not supported. It must be changed to a supported unit.

### Environment:
- Home Assistant version: 2023.3.6
- Energidatastyrelsen version: Most recent
- Operation system: HAOS

**Comment by ChecksumDK** [comment]
It can be seen here:  https://<Your HA>/developer-tools/statistics

**Comment by MTrab** [comment]
Required issue info not provided

**Comment by ChecksumDK** [comment]
The required issue info id "statistics unit "DKK/KWh" is not supported. It must be changed to a supported unit."

**Comment by MTrab** [comment]
First thing - that's NOT what your screenshot says
Second - you have not provided the requested info when creating the issue

**Comment by ChecksumDK** [comment]
Ok
