### ISSUE TITLE
Prices with no tariffs, VAT or extra does not match Nordpool homepage ?

### ISSUE THREAD

**Issue by ujhede** [MTrab/energidataservice#290]
### Describe the issue

Since migrating from the Nordpool integration to yours I have been puzzled why I could not get my old calculation of the "all in kWh price to match what is calculated by this integration.  The tariffs, afgift and VAT published seems to be exactly the same, but the total price does not match exactly.    initially i thought the small difference might be due to some rounding, but today i was asked to explain the calculation to the developer of my EV charging APP and i decided to try and figure out why i cannot replicate your all in price.

I added an instance of your integration with no VAT, tariffs or extra cost, and to my surprise the raw price published is not the same as the one I can see on the Nordpool website.

The only plausible explanation I can think causes this difference is that the  EUR -> DKK exchange rate is not the same.

Below are example numbers for DK2  prices from April 6th.

EnergiData	Nordpool
    1,00824	1,00966
    0,92329	0,92459
    0,89264	0,8939
    0,85791	0,85911
    0,85433	0,85554
    0,92917	0,93048
    1,06009	1,06158
    1,20232	1,20401
    1,16014	1,16177
    0,96294	0,9643
    0,8527	0,8539
    0,78181	0,78291
    0,77377	0,77486
    0,76693	0,76801
    0,77638	0,77747
    0,77861	0,77971
    0,792	0,79311
    0,83113	0,8323
    0,90953	0,91081
    0,86564	0,86686
    0,88141	0,88265
    0,8492	0,8504
    0,81082	0,81196
    0,65572	0,65665

### What version of Home Assistant Core has the issue?

2023.3.6

### What was the last working version of Home Assistant Core?

Don't know

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[config_entry-energidataservice-9c411e1780ee8a19e931925ad33b9a15.json.txt](https://github.com/MTrab/energidataservice/files/11162028/config_entry-energidataservice-9c411e1780ee8a19e931925ad33b9a15.json.txt)

**Comment by MTrab** [comment]
Not sure I know what you want?! You are correct that this is due to the EUR->DKK calculations.
