### ISSUE TITLE
Error in Fixed Price integration

### ISSUE THREAD

**Issue by BFipsen** [MTrab/energidataservice#291]
### Describe the issue

I starten begyndte lavlast tarifen en time for sent, kl. 01:00 hvor det skulle være kl. 00:00 nu kan jeg se at lavlast tarif førs begynder fra kl. 02:00. ydermere, kan jeg se at efter 1 april, er der kun få dage hvor den kommer ned på lavlast, de fleste dage fortsætter den på højlast hele natten (se billeder)

![image](https://user-images.githubusercontent.com/47211841/230711906-f8ed53f1-9ee7-48b5-93a9-bca29c9a092f.png)

![image](https://user-images.githubusercontent.com/47211841/230711942-566d36bf-58b9-48bb-869b-07cda246d426.png)

### What version of Home Assistant Core has the issue?

2023.3.6

### What was the last working version of Home Assistant Core?

--

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[config_entry-energidataservice-ccff61577fdeb6ab1a102291991a78fb.json.txt](https://github.com/MTrab/energidataservice/files/11182834/config_entry-energidataservice-ccff61577fdeb6ab1a102291991a78fb.json.txt)

**Comment by MTrab** [comment]
This is due to the ever returning DST issues. I'll try if I can get this fixed for good.
