### ISSUE TITLE
Negative values in "additional cost" does not work when spot price is negative

### ISSUE THREAD

**Issue by pvprodk** [MTrab/energidataservice#293]
### Describe the issue

I am using a second instance of energidataservice to calculate the earning of sales of surplus energy from solar panels.
When exporting energy the "additional cost" is a negative number, based on "indfødningstarif" and a small amount to the company buying the exported energy. Hence I'm using a template for additional costs:

`{{-0.0623|float}}` or simply `-0.0623` - both gives wrong calculations, but different kind of wrong.

It works perfectly as long as the spot price is 0 or above. But when the spot price is negative (like tomorrow) it is calculated wrong (like the minus is omitted)

![1-1](https://user-images.githubusercontent.com/79306514/230799416-3622cdab-fea8-4c1a-aa8d-47c219baa25b.png)
![1-2](https://user-images.githubusercontent.com/79306514/230799418-3c027915-0d24-487a-8222-6c632f7212c7.png)

### What version of Home Assistant Core has the issue?

core-2023.4.2

### What was the last working version of Home Assistant Core?

N/A

### What type of installation are you running?

Home Assistant Supervised

### Diagnostics information

[config_entry-energidataservice-5f7ef036540628153bbd3d5c438ad9d6.json (1).txt](https://github.com/MTrab/energidataservice/files/11186418/config_entry-energidataservice-5f7ef036540628153bbd3d5c438ad9d6.json.1.txt)

**Comment by affer** [comment]
og med morgendagens priser, (ned til 31 øre excl moms i DK1) så ville det være super at få med i næste opdatering at der kan kalkuleres med negative priser :-) (Søndag 21 maj 2023)

**Comment by pvprodk** [comment]
> og med morgendagens priser, (ned til 31 øre excl moms i DK1) så ville det være super at få med i næste opdatering at der kan kalkuleres med negative priser :-) (Søndag 21 maj 2023)

Enig :)

**Comment by woopstar** [comment]
Could this be the line that causes the issue when price is negative?

https://github.com/MTrab/energidataservice/blob/master/custom_components/energidataservice/sensor.py#LL688C34-L688C48

**Comment by MTrab** [comment]
Could be

**Comment by MTrab** [comment]
I think this is rather a Jinja problem in how negative numbers are interpreted.

Try using `{{"-0.0623"|float}}` instead.
You can try this in the Template Editor in Home assistant.

![image](https://github.com/MTrab/energidataservice/assets/14296463/80d1c155-a33b-46bf-abba-947b54d0c3de)

**Comment by affer** [comment]
today i tested with the following line:
{{"-0.0256"|float}}

from 11-13 price today was positive, and the caclulation seemed correct, i got a negative value as result 👍🏻 and energy data dashboard calculated the sale as an expense.

from 13-15 the price was negative, and the calculation resulted in a positive value :-/ energy data dashboard calculated it as an income, it should have been an expense. 

below screenshot is from nordpool prices today. 
<img width="209" alt="Screenshot 2023-06-25 at 15 31 05" src="https://github.com/MTrab/energidataservice/assets/3717164/6866c1c6-43a1-48a3-b59d-cdbc9df74d35">
<img width="2287" alt="Screenshot 2023-06-25 at 15 31 51" src="https://github.com/MTrab/energidataservice/assets/3717164/5816ccb4-5301-4560-87d2-4ec3a89de923">
above screenshot shows the two hours that goes positive, the result should have been a greater negative value. 

did i miss something?

**Comment by affer** [comment]
with today prices i can see when price is positive the setting {{"-0.0256"|float}} is subtracted from the "spotprice"  when the official price goes negative, i still get a smaller negative number, suspecting a larger negative number.

as seen in attached files.. when price is positive, the value is correct and goes negative, when the value is negative, i do not get a greater negative value, it seems that the {{"-0.0256"|float}} is added instead og subtracted. (expecting a larger negative value, not a smaller negativer value) 
<img width="475" alt="Screenshot 2023-07-02 at 06 31 13" src="https://github.com/MTrab/energidataservice/assets/3717164/a3039534-453f-4387-b73f-e679c811ae3e">
<img width="201" alt="Screenshot 2023-07-02 at 06 30 08" src="https://github.com/MTrab/energidataservice/assets/3717164/5e2b32da-21a7-4822-b3e6-24ec0573d5f1">
