### ISSUE TITLE
Finland's VAT is 10% not 24%

### ISSUE THREAD

**Issue by jeveli** [MTrab/energidataservice#297]
### Describe the feature you wish to make a request for

Is there a way to edit this, we have 10% vat until 1.5.

**Comment by MTrab** [comment]
So it's a temporary lowering of VAT?

**Comment by MTrab** [comment]
For now, you can just change this line to 0.1 rather than 0.24:

const.py - line 86:
`    "FI": [CURRENCY_LIST["EUR"], "Finland", "Finland", 0.24],`

to
`    "FI": [CURRENCY_LIST["EUR"], "Finland", "Finland", 0.1],`
