### ISSUE TITLE
Tariff not refreshing at night

### ISSUE THREAD

**Issue by nikobh** [MTrab/energidataservice#298]
### Describe the issue

When tariffs change from day to day, the integration should refresh the tariff every night for the coming day. This does not happen.
The screenshot is from my installation taken at 11.43 where the tariff is supposed to be 0.074 all day.
When reloading the integration the new tariff is fetched and the integration works as intended again.

![Skærmbillede 2023-04-15 114349](https://user-images.githubusercontent.com/45816930/232210670-e3a3f585-8f19-4a45-89e7-8af4d14a2033.png)

### What version of Home Assistant Core has the issue?

core-2023.4.4

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[config_entry-energidataservice-fe9621441b5d36fe221181b8ed1f60aa.json.txt](https://github.com/MTrab/energidataservice/files/11239213/config_entry-energidataservice-fe9621441b5d36fe221181b8ed1f60aa.json.txt)

**Comment by larserhardsen** [comment]
I have seen this exception the past few nights, where EDS failed to get prices.

```
Logger: async_retrying_ng
Source: custom_components/energidataservice/tariffs/energidataservice/__init__.py:155
Integration: Energi Data Service (documentation, issues)
First occurred: 00:09:02 (2 occurrences)
Last logged: 00:10:12

ClientResponseError -> Attempts (5) are over for <function Connector.async_call_api at 0x7f7cb489f7f0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/async_retrying_ng/__init__.py", line 118, in wrapped
    ret = await ret
  File "/config/custom_components/energidataservice/tariffs/energidataservice/__init__.py", line 155, in async_call_api
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://api.energidataservice.dk/dataset/DatahubPricelist?filter=%7B%22Note%22:%5B%22Elafgift%22,%22Systemtarif%22,%22Transmissions+nettarif%22%5D%7D&limit=500')

```

**Comment by mm98** [comment]
I've seen this numerous times right after midnight. It looks like `https://api.energidataservice.dk` is busy right after midnight and until 2AM (is a bit random). I've added an automation, that automaticly updates `EDS` at 2:30 AM. This solved the problem for me. EDS is trying 5 times and gives up - which is the correct way to handle this IMO.

**Comment by larserhardsen** [comment]
I guess you are not getting prices for the hours 00 and 01 then?

Without knowing how the EDS integration works at all, I think the most gentle way of handling this would be to keep the "tomorrow's prices" until they succesfully could be replaced by real data from EDS. Is that possible?
________________________________

**Comment by MTrab** [comment]
That is what already happens. Tomorrow prices are moved to Today.
The refresh at midnight are only for tariff data

**Comment by cokeman0** [comment]
Hi,

For el-net kongerslev the tarrif is 0.50, for all hours of the day. But we are using tarrif model 3 so 3 different during the day. I dont know if the problem is on the api. As watts app also have the same issue with both el-net kongerslev and n1
