### ISSUE TITLE
[FR]: Upper limit (DKK/kWh) - EWII, Grøn Prisloft

### ISSUE THREAD

**Issue by mm98** [MTrab/energidataservice#301]
### Describe the feature you wish to make a request for

EWII has started offering a new product (`Grøn Prisloft`) that extends the existing `Grøn Indkøbspris`. This is also based on the hourly kWh price (with an additional fee), but with an upper limit.

### Describe alternatives you've considered

Are there any way to implement this in the existing version? I have looked at the WIKI, but haven't been able to find anything mentioning setting upper or lower limits.

### Additional context

More info [here](https://www.ewii.dk/privat/el/groen-el-med-prisloft/).

**Comment by MTrab** [comment]
This would be something for templating in the additional costs, not as a feature I think
