### ISSUE TITLE
Sensor doesn't update, gets stuck

### ISSUE THREAD

**Issue by Dennisreneholm** [MTrab/energidataservice#307]
### Describe the issue

Sometimes the sensor does not update, and just keeps the former value.
I haven't noticed a pattern in this. If i manually reload the integration, it updates just fine.
![image](https://github.com/MTrab/energidataservice/assets/5224930/a521ab19-a205-4b69-92fb-bfbd46f83cd5)
Here's an example, it stopped updating at 23:00, and i had to manually reload, and then it works fine.

### What version of Home Assistant Core has the issue?

core-2023.5.4

### What type of installation are you running?

Home Assistant Container

### Diagnostics information

[config_entry-energidataservice-92c63ec584adde9f7ece03ef53aee831.json.txt](https://github.com/MTrab/energidataservice/files/11673317/config_entry-energidataservice-92c63ec584adde9f7ece03ef53aee831.json.txt)

**Comment by Alphaemef** [comment]
I have the exact same issue. Nordpool went through the same after an HA update, but they seem to have fixed it. Anything that would tell the integration to fetch new data (so we can automate it) would help.

**Comment by kenni** [comment]
I experience the same issue, but have noticed that it is ***only*** the Entity values that gets stuck - the values are downloaded correctly and are shown in the entity attributes. If you look at the "Raw today" and "Raw tomorrow" values, the values are all there and correct, while the Entity History seems to get stuck from 23:00 until the next time it updates. Let me know if I can provide anything to debug this issue.

![image](https://github.com/MTrab/energidataservice/assets/486971/ec859521-764c-459a-a99d-eef94767244b)

<img width="254" alt="image" src="https://github.com/MTrab/energidataservice/assets/486971/5d23674c-ab16-47cf-b30b-7a87d16c09f8">

**Comment by MTrab** [comment]
Are this always happening at the same time of the day?
Anything else happening at that specific time (backup or other)

Have never seen this issue on any of the installations I manage, one running RPi 4, 2 on Proxmox and one on ODroid.

**Comment by kenni** [comment]
> Are this always happening at the same time of the day?

Yes, in my case the entity gets stuck at 23:01 and is fixed the next day at 13:34, where I automatically reload the Energi Data Service through an automation - or before, if I restart HA manually for other reasons.

> Anything else happening at that specific time (backup or other)

I'm running HAOS on Proxmox. I've checked and the Proxmox host performs a backup at 03:00 (I've verified that timezone etc. is correct, which it is, so it *is* at 03:00). I do not have any automations in HA that runs after 20:00.

Going back in my history, I can see that it got stuck 12 times over the past ~40 days. I do not see any patterns in the occurrence. I have history for the entity back to the 1st of March and I can see that the first occurrence was all the way back to the 18th of March 2023 - so the issue has been around for some time. 

Pattern for the past ~40 days:
<img width="718" alt="image" src="https://github.com/MTrab/energidataservice/assets/486971/823111c6-299c-4307-82ba-d1cfdf557fed">

**Comment by MTrab** [comment]
Really strange. Will try a few different things to try and mitigate this. Not sure when I have a fix ready though

**Comment by kenni** [comment]
> I have the exact same issue. Nordpool went through the same after an HA update, but they seem to have fixed it.

@Alphaemef Can you share a link or some more info? I've been searching through the Github repository of the Nordpool integration and parts of the HA repository/changelogs, but I haven't been able to identify any such changes.

**Comment by Dennisreneholm** [comment]
I can also confirm it happens at 23:00
Did not notice that before
![image](https://github.com/MTrab/energidataservice/assets/5224930/54f00ec1-53fb-46eb-a554-561c0848c788)

Happened again last night.

**Comment by kenni** [comment]
> I can also confirm it happens at 23:00 Did not notice that before ![image](https://user-images.githubusercontent.com/5224930/245693081-54f00ec1-53fb-46eb-a554-561c0848c788.png)
> 
> Happened again last night.

@Dennisreneholm, interesting, mine also got stuck yesterday. Looking at your initial post, it seems like yours got stuck on the 6th and the 7th as well - so did mine. Could you try to see on which dates during this month that yours got stuck? Mine got stuck on:
02/06/2023 @ 23:00
05/06/2023 @ 23:00 
06/06/2023 @ 23:00
07/06/2023 @ 23:00
13/06/2023 @ 23:00

**Comment by MTrab** [comment]
Think I might have tracked down the bug. Currently testing fixes.

**Comment by MTrab** [comment]
Apparently not fully fixed, so not included in this latest release.

It's really strange, seems like it's (AGAIN!!) something with timezones, being the issue for this.

**Comment by sdmoeller** [comment]
I have the same issue
