### ISSUE TITLE
Tarrif 3.0

### ISSUE THREAD

**Issue by cokeman0** [MTrab/energidataservice#308]
### Describe the issue

EDS benytter ikke Tarif model 3.0 priser.

### What version of Home Assistant Core has the issue?

2023.06.1

### What was the last working version of Home Assistant Core?

-

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[config_entry-energidataservice-9816877732e63ae69df4935f68f263a7.json.txt](https://github.com/MTrab/energidataservice/files/11725801/config_entry-energidataservice-9816877732e63ae69df4935f68f263a7.json.txt)

### Additional information

Hvis jeg kigger på energidataservice.dk kan jeg finde de rigtige priser

El-net Kongerslev A/S | 5790002502699 | D03 | C-Tarif | C-Kunder Nettarif | C-Kunder Nettarif efter tarifmodel 3.0 | 2023-06-01 | 2023-10-01 | D02 | 0,242200 | 0,242200 | 0,242200 | 0,242200 | 0,242200 | 0,242200 | 0,363300 | 0,363300 | 0,363300 | 0,363300 | 0,363300 | 0,363300 | 0,363300 | 0,363300 | 0,363300 | 0,363300 | 0,363300 | 0,944500 | 0,944500 | 0,944500 | 0,944500 | 0,363300 | 0,363300 | 0,363300 | 0 | 0 | PT1H

I EDS på HA står:
tariffs:
attribution: Data sourced from Energi Data Service
net_operator: El-net Kongerslev
  additional_tariffs:
    transmissions_nettarif: 0.073
    systemtarif: 0.068
    elafgift: 0.01
  tariffs:
    '0': 0.5
    '1': 0.5
    '2': 0.5
    '3': 0.5
    '4': 0.5
    '5': 0.5
    '6': 0.5
    '7': 0.5
    '8': 0.5
    '9': 0.5
    '10': 0.5
    '11': 0.5
    '12': 0.5
    '13': 0.5
    '14': 0.5
    '15': 0.5
    '16': 0.5
    '17': 0.5
    '18': 0.5
    '19': 0.5
    '20': 0.5
    '21': 0.5
    '22': 0.5
    '23': 0.5

**Comment by cokeman0** [comment]
Hej,

Dette issue, gælder også for N1 kan jeg se, da jeg sætte en op for mit sommerhus.

EDS:
tariffs:
  '0': 0.408
  '1': 0.408
  '2': 0.408
  '3': 0.408
  '4': 0.408
  '5': 0.408
  '6': 0.408
  '7': 0.408
  '8': 0.408
  '9': 0.408
  '10': 0.408
  '11': 0.408
  '12': 0.408
  '13': 0.408
  '14': 0.408
  '15': 0.408
  '16': 0.408
  '17': 0.408
  '18': 0.408
  '19': 0.408
  '20': 0.408
  '21': 0.408
  '22': 0.408
  '23': 0.408

N1.dk:
![image](https://github.com/MTrab/energidataservice/assets/6389802/9345424f-8321-47c1-b13a-81839862c8f4)

**Comment by MTrab** [comment]
Det gælder for Kongerslev - det er den eneste jeg har set issues på skulle have forkerte tariffer.

**Comment by cokeman0** [comment]
Ok, tak for hjælpen... :-)

et fantastisk værktøj....

**Comment by mediaNen** [comment]
> Det gælder for Kongerslev - det er den eneste jeg har set issues på skulle have forkerte tariffer.

Det gælder også for Energi Nord Net. Jeg har netop kontrolleret min egen og den står til fast tarif  selvom den bør være variabel ifølge NordEnergiNets nye priser pr. 1/7.

![NordEnergiNet](https://github.com/MTrab/energidataservice/assets/115061247/b9ba9472-ef69-4f66-984e-2876fc8bf65b)

Er det noget jeg selv kan fikse?
