### ISSUE TITLE
[FR]: Different Tariffes. If not in C spectrum, but eg. B-Low/High.

### ISSUE THREAD

**Issue by ProdanAS** [MTrab/energidataservice#316]
### Describe the feature you wish to make a request for

Select the different Tariffes at the different providers. In this case, I'm at b-low but seems like the tariffs are hardcoded using C Tariff.

**Comment by MTrab** [comment]
I only have knowledge of the C tariffs, that's why these are the only ones used by this plugin.
I don't even know what the other tariffs does.
But you can always add them yourself in `custom_components/energidataservice/tariffs/energidataservice/chargeowners.py`
The correct type you need to find in the Energi Data Service API.

**Comment by ProdanAS** [comment]
When the output is received from energi data. In the api feed. There's prices referenced as b-lav instead of C



Sendt fra min iPhone


Venlig hilsen / Best regards / Freundliche Grüße

Michael Bach
IT-Ansvarlig
[cid:prodan-sommer_a4196d54-4b5e-4147-a17b-b9e3f0b8980c.png]

Bemærk vi holder ferielukket i uge 29 & 30
Prodan are closed for the holiday week 29 & 30

Prodan A/S      +45 87 538 538<tel:+4587538538> (phone)
Tåsingevej 1    +45 87 538 501<tel:87%20538%20501> (direct)

DK-8940 Randers SV      +45 51 201 918<tel:51%20201%20918> (mobile)

[cid:www_5ac155d3-06ae-4f0d-a1d2-32b7fb1e6094.png]<https://www.prodan.dk>   [cid:facebook_cbf9d399-4230-42e7-8634-0d6128034b23.png] <https://www.facebook.com/prodandk>    [cid:linkedin_89b50ad4-bf5f-4e9c-9fac-55cd1b65b0f4.png] <https://www.linkedin.com/company/2855135/>    [cid:youtube_703bf9ab-4a9a-4a43-9f01-3700bd1a3486.png] <https://www.youtube.com/channel/UCedkn4RGqLRXOt_-rhIXlgA>

[cid:1x1_8748672d-f305-4acb-bf0c-093fdfd42d1c.png]

[cid:9001_80px_79f05ecf-736b-4129-8a97-78530cf2ccf1.png]<https://prodan.dk/wp-content/uploads/2021/02/ISO_9001_14001_-_2020.pdf>[cid:14001_5b392f0a-21cf-4ff4-b24a-55b55785744f.png]<https://prodan.dk/wp-content/uploads/2021/02/ISO_9001_14001_-_2020-1.pdf>[cid:3834_9510ec7d-2558-4112-97d2-e58cb288cd63.png]<https://prodan.dk/wp-content/uploads/2021/02/ISO_3834_-_2020.pdf>[cid:1090_55576ac9-4f48-4c64-9df8-6f0b12aefb3d.png]<https://prodan.dk/wp-content/uploads/2021/02/EN_1090_-_2020.pdf>
[cid:QRc6a2b8cc-39a0-4bee-91f3-af24c494e60b.png]Download v-card

        [cid:aaa_8ac4b16f-d843-4497-bf45-7baa76d9855d.png]


Den 26. jun. 2023 kl. 22.20 skrev Malene Trab ***@***.***>:

﻿

I only have knowledge of the C tariffs, that's why these are the only ones used by this plugin.
I don't even know what the other tariffs does.
But you can always add them yourself in custom_components/energidataservice/tariffs/energidataservice/chargeowners.py
The correct type you need to find in the Energi Data Service API.

**Comment by MTrab** [comment]
I know - but I have no knowledge of anyone using these until now?!

**Comment by ProdanAS** [comment]
The different tariffs is for eg. Companies that utilitize more power than an regular consumer. Meaning more than 50 amps socket

I'm trying to setup an automatic scaling of a solar array. But I need to have HA aware of the current tariff. So the automatic tariff update is preferred

Sendt fra min iPhone


Venlig hilsen / Best regards / Freundliche Grüße

Michael Bach
IT-Ansvarlig
[cid:prodan-sommer_a4196d54-4b5e-4147-a17b-b9e3f0b8980c.png]

Bemærk vi holder ferielukket i uge 29 & 30
Prodan are closed for the holiday week 29 & 30

Prodan A/S      +45 87 538 538<tel:+4587538538> (phone)
Tåsingevej 1    +45 87 538 501<tel:87%20538%20501> (direct)

DK-8940 Randers SV      +45 51 201 918<tel:51%20201%20918> (mobile)

[cid:www_5ac155d3-06ae-4f0d-a1d2-32b7fb1e6094.png]<https://www.prodan.dk>   [cid:facebook_cbf9d399-4230-42e7-8634-0d6128034b23.png] <https://www.facebook.com/prodandk>    [cid:linkedin_89b50ad4-bf5f-4e9c-9fac-55cd1b65b0f4.png] <https://www.linkedin.com/company/2855135/>    [cid:youtube_703bf9ab-4a9a-4a43-9f01-3700bd1a3486.png] <https://www.youtube.com/channel/UCedkn4RGqLRXOt_-rhIXlgA>

[cid:1x1_8748672d-f305-4acb-bf0c-093fdfd42d1c.png]

[cid:9001_80px_79f05ecf-736b-4129-8a97-78530cf2ccf1.png]<https://prodan.dk/wp-content/uploads/2021/02/ISO_9001_14001_-_2020.pdf>[cid:14001_5b392f0a-21cf-4ff4-b24a-55b55785744f.png]<https://prodan.dk/wp-content/uploads/2021/02/ISO_9001_14001_-_2020-1.pdf>[cid:3834_9510ec7d-2558-4112-97d2-e58cb288cd63.png]<https://prodan.dk/wp-content/uploads/2021/02/ISO_3834_-_2020.pdf>[cid:1090_55576ac9-4f48-4c64-9df8-6f0b12aefb3d.png]<https://prodan.dk/wp-content/uploads/2021/02/EN_1090_-_2020.pdf>
[cid:QRaa6d1299-01c4-4e27-b151-97ab4f5d6386.png]Download v-card

        [cid:aaa_8ac4b16f-d843-4497-bf45-7baa76d9855d.png]


Den 26. jun. 2023 kl. 22.27 skrev Malene Trab ***@***.***>:

﻿

I know - but I have no knowledge of anyone using these until now?!

**Comment by ProdanAS** [comment]
I've managed to edit the module in the Chargeovners, to use B2D instead. The calculation seems a little off. As the Nordpool right now is 0,39 and the total cost returned states 66,6666. The Tariff is 23,7,. Are the reason why, because you add the 0.01 in taxes ?

**Comment by MTrab** [comment]
Guess it's the wrong tariff you have added?!
Shouldn't be any differences if using one instead of another, as long as it's the right one

**Comment by ProdanAS** [comment]
Does it not add the nordpool spot price as well. What is the calculation?



Sendt fra min iPhone


Venlig hilsen / Best regards / Freundliche Grüße

Michael Bach
IT-Ansvarlig
[cid:prodan-sommer_a4196d54-4b5e-4147-a17b-b9e3f0b8980c.png]

Bemærk vi holder ferielukket i uge 29 & 30
Prodan are closed for the holiday week 29 & 30

Prodan A/S      +45 87 538 538<tel:+4587538538> (phone)
Tåsingevej 1    +45 87 538 501<tel:87%20538%20501> (direct)

DK-8940 Randers SV      +45 51 201 918<tel:51%20201%20918> (mobile)

[cid:www_5ac155d3-06ae-4f0d-a1d2-32b7fb1e6094.png]<https://www.prodan.dk>   [cid:facebook_cbf9d399-4230-42e7-8634-0d6128034b23.png] <https://www.facebook.com/prodandk>    [cid:linkedin_89b50ad4-bf5f-4e9c-9fac-55cd1b65b0f4.png] <https://www.linkedin.com/company/2855135/>    [cid:youtube_703bf9ab-4a9a-4a43-9f01-3700bd1a3486.png] <https://www.youtube.com/channel/UCedkn4RGqLRXOt_-rhIXlgA>

[cid:1x1_8748672d-f305-4acb-bf0c-093fdfd42d1c.png]

[cid:9001_80px_79f05ecf-736b-4129-8a97-78530cf2ccf1.png]<https://prodan.dk/wp-content/uploads/2021/02/ISO_9001_14001_-_2020.pdf>[cid:14001_5b392f0a-21cf-4ff4-b24a-55b55785744f.png]<https://prodan.dk/wp-content/uploads/2021/02/ISO_9001_14001_-_2020-1.pdf>[cid:3834_9510ec7d-2558-4112-97d2-e58cb288cd63.png]<https://prodan.dk/wp-content/uploads/2021/02/ISO_3834_-_2020.pdf>[cid:1090_55576ac9-4f48-4c64-9df8-6f0b12aefb3d.png]<https://prodan.dk/wp-content/uploads/2021/02/EN_1090_-_2020.pdf>
[cid:QR3248366c-b3b1-4366-84f5-9838701b6783.png]Download v-card

        [cid:aaa_8ac4b16f-d843-4497-bf45-7baa76d9855d.png]


Den 27. jun. 2023 kl. 18.30 skrev Malene Trab ***@***.***>:

﻿

Guess it's the wrong tariff you have added?!
Shouldn't be any differences if using one instead of another, as long as it's the right one

**Comment by MTrab** [comment]
Spotprice+tariffs+additional costs template+vat

**Comment by ProdanAS** [comment]
Wierd this should be the same result. But it was 1 off. And I have not any additional costs. Can I print the result/values used for the result?

Sendt fra min iPhone


Venlig hilsen / Best regards / Freundliche Grüße

Michael Bach
IT-Ansvarlig
[cid:prodan-sommer_a4196d54-4b5e-4147-a17b-b9e3f0b8980c.png]

Bemærk vi holder ferielukket i uge 29 & 30
Prodan are closed for the holiday week 29 & 30

Prodan A/S      +45 87 538 538<tel:+4587538538> (phone)
Tåsingevej 1    +45 87 538 501<tel:87%20538%20501> (direct)

DK-8940 Randers SV      +45 51 201 918<tel:51%20201%20918> (mobile)

[cid:www_5ac155d3-06ae-4f0d-a1d2-32b7fb1e6094.png]<https://www.prodan.dk>   [cid:facebook_cbf9d399-4230-42e7-8634-0d6128034b23.png] <https://www.facebook.com/prodandk>    [cid:linkedin_89b50ad4-bf5f-4e9c-9fac-55cd1b65b0f4.png] <https://www.linkedin.com/company/2855135/>    [cid:youtube_703bf9ab-4a9a-4a43-9f01-3700bd1a3486.png] <https://www.youtube.com/channel/UCedkn4RGqLRXOt_-rhIXlgA>

[cid:1x1_8748672d-f305-4acb-bf0c-093fdfd42d1c.png]

[cid:9001_80px_79f05ecf-736b-4129-8a97-78530cf2ccf1.png]<https://prodan.dk/wp-content/uploads/2021/02/ISO_9001_14001_-_2020.pdf>[cid:14001_5b392f0a-21cf-4ff4-b24a-55b55785744f.png]<https://prodan.dk/wp-content/uploads/2021/02/ISO_9001_14001_-_2020-1.pdf>[cid:3834_9510ec7d-2558-4112-97d2-e58cb288cd63.png]<https://prodan.dk/wp-content/uploads/2021/02/ISO_3834_-_2020.pdf>[cid:1090_55576ac9-4f48-4c64-9df8-6f0b12aefb3d.png]<https://prodan.dk/wp-content/uploads/2021/02/EN_1090_-_2020.pdf>
[cid:QR2eb834e0-74d1-4bf3-8130-c47a789b707c.png]Download v-card

        [cid:aaa_8ac4b16f-d843-4497-bf45-7baa76d9855d.png]


Den 27. jun. 2023 kl. 20.44 skrev Malene Trab ***@***.***>:

﻿

Spotprice+tariffs+additional costs template+vat

**Comment by ProdanAS** [comment]
I've finally found out the "Issiue" I counts the static Tariffs as well. :) My bad. It works now, after changing the charge owner.
