### ISSUE TITLE
FLOW elnet  Fixed Price

### ISSUE THREAD

**Issue by rbjoensen** [MTrab/energidataservice#318]
### Describe the issue

Prisen er den samme hele døgnet når Fixed Price er valgt.

### What version of Home Assistant Core has the issue?

Latest_version 

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

`None`

**Comment by MTrab** [comment]
Ja?! Det er jo ligesom det fixed price er til 🤷🏼‍♀️

**Comment by rbjoensen** [comment]
Fixed Price med FLOW elnet
![Screenshot_20230628_121203_Home Assistant](https://github.com/MTrab/energidataservice/assets/72686635/f05a124b-f011-49ee-80e7-2a9569ad7549)

**Comment by rbjoensen** [comment]
Fixed prise med Elnet Midt

![Screenshot_20230628_121255_Home Assistant](https://github.com/MTrab/energidataservice/assets/72686635/45580629-f96b-494b-a397-829fc05d8b30)

**Comment by MTrab** [comment]
Hvis FLOW ikke har variable afgifter, så er det jo ikke variabelt.

Du havde ikke vedhæftet diagnostic som krævet, så var lidt svært at se hvad du havde lavet.

**Comment by MTrab** [comment]
Nu fik jeg så lige lidt tid til at tjekke - og så vidt jeg kan se, så har FLOW faste tariffer hele døgnet rundt, og ikke variable som de fleste andre har.
Så jeg ser ingen fejl her.

**Comment by MTrab** [comment]
Går ud fra dette ikke er et issue alligevel, når ikke der har været yderligere reaktion
