### ISSUE TITLE
New prises dosnt show until integration is refreshed

### ISSUE THREAD

**Issue by andlo** [MTrab/energidataservice#319]
### Describe the issue

It seems like new prises isnt shown until the integration is beeing refreshed.

I have notised this for some days, but werent sure if the problem were my setup og the integration. Still arent sure. But I can fix it by reloading integrtion.

### What version of Home Assistant Core has the issue?

core-2023.6.3

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

...

**Comment by MTrab** [comment]
Please attach diagnostics as required

**Comment by lauer** [comment]
I had same issue, but I don't think the diagnostics help after reloading - because it just works hereafter. 
(running 2023.6.1)
[config_entry-energidataservice-823d46d0426fb5c2b4d8df7fdfa27105.json.txt](https://github.com/MTrab/energidataservice/files/11907683/config_entry-energidataservice-823d46d0426fb5c2b4d8df7fdfa27105.json.txt)

**Comment by andlo** [comment]
Atatched is to diagnostics. One from before I reload the addin and after. Before reload prises were not updated, but after they were.

[BEFORE config_entry-energidataservice-b8a89d1e40a226b6a8f540a7b10b791c.json.txt](https://github.com/MTrab/energidataservice/files/11916152/BEFORE.config_entry-energidataservice-b8a89d1e40a226b6a8f540a7b10b791c.json.txt)
[AFTER config_entry-energidataservice-b8a89d1e40a226b6a8f540a7b10b791c.json (1).txt](https://github.com/MTrab/energidataservice/files/11916153/AFTER.config_entry-energidataservice-b8a89d1e40a226b6a8f540a7b10b791c.json.1.txt)

**Comment by LasseLegarth** [comment]
Same issue here :(

**Comment by KennethLavrsen** [comment]
Me too

**Comment by onrust** [comment]
Same here for a week or so.

**Comment by MTrab** [comment]
Same for everyone, and won't be fixed until next week

**Comment by KennethLavrsen** [comment]
We will survive. Enjoy your vacation. The meetoos are not meant to rush anyone. Just data points to help.

**Comment by kfjellerup** [comment]
Input for troubleshooting: Reverting back to 1.3.4 removes the problem

**Comment by MTrab** [comment]
And introduces another ;)

**Comment by ujhede** [comment]
For anyone that has this issue daily here is a workaround automation until the issue can be fixed. This will reload the integration at 13:45 if tomorrow_valid is not set.

entity_id is the is of the Energi Data service as found is  /root/config/.storage/core.config_entries

alias: Reload Energi Data Service
description: ""
trigger:
  - platform: time
    at: "13:45:00"
condition:
  - condition: template
    value_template: "{{ is_state_attr('sensor.energi_data_service','tomorrow_valid',0)}}"
action:
  - service: homeassistant.reload_config_entry
    data:
      entry_id: xxxxxxxxxx
mode: single

**Comment by MTrab** [comment]
DO NOT use the same time all of you!!
