### ISSUE TITLE
New installation of Energi data service not working. 

### ISSUE THREAD

**Issue by andersstou1** [MTrab/energidataservice#332]
### Describe the issue

I have installed the energi data service on my HA friday morning. But when i look in the entity it just comes with the following error.

![image](https://github.com/MTrab/energidataservice/assets/45497294/5ca83023-b743-4fc9-b827-09595c3a46a2)
 

### What version of Home Assistant Core has the issue?

2023.7.3

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[config_entry-energidataservice-960cdcae490372d98a2c97e5a27008c8.json (1).txt](https://github.com/MTrab/energidataservice/files/12208028/config_entry-energidataservice-960cdcae490372d98a2c97e5a27008c8.json.1.txt)

**Comment by MTrab** [comment]
Please check and attach the relevant log entries from home-assistant.log

**Comment by andersstou1** [comment]
Finally found the error deep in the logs. Was a api key that was wrong for carnot.dk
