### ISSUE TITLE
Wiki update: New additional cost for Norlys FlexEl

### ISSUE THREAD

**Issue by JensKemp** [MTrab/energidataservice#340]
### Describe the issue

According to https://stromligning.dk/live additional cost for Norlys FlexEl is now: {{0.08|float(0)}}

### What version of Home Assistant Core has the issue?

core-2023.8.2

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

None

**Comment by MTrab** [comment]
Wiki updated
