### ISSUE TITLE
N1 and Vindstød DanskVind terrif error

### ISSUE THREAD

**Issue by MartinNorgaardDK** [MTrab/energidataservice#343]
### Describe the issue

When setting up using N1 and Vindstød DanskVind using {{0.00625|float(0)}}, it shows wrong price.
Think the issue is the N1 discount is not calculated.

Rabat på nettarif N1 A/S
kl. 00.00 - 00.00 | -0,27550 kr.

### What version of Home Assistant Core has the issue?

core-2023.8.3

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_energidataservice_2023-08-24T06-31-36.433Z.log](https://github.com/MTrab/energidataservice/files/12426099/home-assistant_energidataservice_2023-08-24T06-31-36.433Z.log)

**Comment by MTrab** [comment]
Please see https://github.com/MTrab/energidataservice/issues/334#issuecomment-1678517119
