### ISSUE TITLE
Error 500 internal server error

### ISSUE THREAD

**Issue by stofakiller** [MTrab/energidataservice#347]
### Describe the issue

I saw last evening that i didt got data, and i triede to reload the integration, error 500. I removed then the integration/addon and rebooted HA, and installed it again, same error... And again this morning still error 500

### What version of Home Assistant Core has the issue?

2023.9.0b0

### What type of installation are you running?

Home Assistant Supervised

### Diagnostics information

I cant provide logs, because i cant install it in HA at the moment

### Additional information

I cant provide logs, because i cant install it in HA at the moment

**Comment by MTrab** [comment]
Error 500 is a server error - nothing I can do much against, other than trying to see if I can catch the error.
Can't see anything in my logs, so not sure why you see the error.

**Comment by stofakiller** [comment]
Can it be, that i just yesterday upgraded to 2023.9.0.b0?

**Comment by MTrab** [comment]
Just tried 9.0b0 and it works like intended here.

**Comment by stofakiller** [comment]
When trying to install then integration, it get this:
Konfigurationsflow kunne ikke indlæses: 500 Internal Server Error Server got itself in trouble

But i found a api url in your code (https://api.energidataservice.dk/dataset/elspotprices), and that works perfect in my browser

I make another instance of HA in my proxmox, with earlier backup(s)

**Comment by MTrab** [comment]
OH! So it's during config?! See that was a vital piece of information.
Will test right away.

**Comment by MTrab** [comment]
Nope - still no errors. Not even with all the bells and whistles enabled.

**Comment by stofakiller** [comment]
I did a clean (stable) install of HA, installed HACS and energidataservice... Everything work perfekt, then i joined the beta channel and upgrade supervisor and core, and did a reboot... Now it cant load anymore and i got this in the core log:

Logger: homeassistant.setup
Source: setup.py:209
First occurred: 11.34.42 (1 occurrences)
Last logged: 11.34.42

Setup failed for custom integration energidataservice: Requirements for energidataservice not found: ['async-retrying-ng==0.1.1'].

**Comment by stofakiller** [comment]
And regarding the async-retrying i also got this in the HA log

Logger: homeassistant.util.package
Source: util/package.py:108
First occurred: 11.34.38 (3 occurrences)
Last logged: 11.34.42

Unable to install package async-retrying-ng==0.1.1: ERROR: Cannot install async-retrying-ng==0.1.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip

**Comment by MTrab** [comment]
Arh! Made a complete wipe of my devcontainer and now I have the issue as well.

**Comment by MTrab** [comment]
Could you test changing `"async-retrying-ng==0.1.1"` to `"async-retrying-ng==0.1.2"` in the `manifest.json` file?

**Comment by stofakiller** [comment]
I was just changing it as you wrote :-)
Both my produktion HA, and my new created test HA works (y)

But there is no checking when entering API key for carnot ;-)

Thanks a lot for your quick help/response :-)

**Comment by MTrab** [comment]
Will push a release during the day, to be ready for next HA release.
Thanks for the heads-up though :)
