### ISSUE TITLE
Forecast bug

### ISSUE THREAD

**Issue by plaiddk** [MTrab/energidataservice#352]
### Describe the issue

First of all - Big thanks for all the work you have done so far. Its brilliant! 

Im not sure if its me or if it is a bug. But my forecast looks kinda weird. I should have done as you mention in your wiki. First creating the templates and then the card. 
![Screenshot_210](https://github.com/MTrab/energidataservice/assets/20297081/4dae3a67-4d91-45c1-83d0-c1d624a09f23)

### What version of Home Assistant Core has the issue?

	core-2023.8.4

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

Empty

**Comment by MTrab** [comment]
Yeah - just noticed myself. Seems like some issue with the change of month. Fix will be up when I have something tested and ready.
