### ISSUE TITLE
[FR]: Add Aal Elnet to supplier list

### ISSUE THREAD

**Issue by sumwun99** [MTrab/energidataservice#365]
### Describe the feature you wish to make a request for

I am missing “Aal Elnet” to the list over supplier to get the correct tarif for my area.

**Comment by MTrab** [comment]
Where in the country does this supplier reside?

**Comment by sumwun99** [comment]
> Where in the country does this supplier reside?

In Varde Kommune (6840). It’s within N1’s area, but they have their own tarifs.
