### ISSUE TITLE
Carnot error makes energidataservice not working

### ISSUE THREAD

**Issue by stofakiller** [MTrab/energidataservice#366]
### Describe the issue

When enabled Carnot, and eg there is error with the connection or api credentials error, then energidataservice is not working at all… When reconfigured without Carnot enabled, everything is working again…

### What version of Home Assistant Core has the issue?

2023.9.1

### What type of installation are you running?

Home Assistant Supervised

### Diagnostics information

In logs I can see credentials error from Carnot URL, even that the key is correct and is normally working.

**Comment by MTrab** [comment]
ALWAYS include ALL relevant log entries, otherwise it's almost impossible to do anything.

**Comment by stofakiller** [comment]
Sure 😊
Can you use this in the meantime?

Denne fejl stammer fra en brugerdefineret integration.

Logger: custom_components.energidataservice.forecasts.carnot
Source: custom_components/energidataservice/forecasts/carnot/__init__.py:75
Integration: Energi Data Service (documentation, issues)
First occurred: 11. september 2023 kl. 09.58.58 (5 occurrences)
Last logged: 09.20.18

API returned error 401, Validation error - check your credentials!

The credentials are correct and normally working...
![image](https://github.com/MTrab/energidataservice/assets/11716346/beddb39e-3c9f-44e9-b554-7ca8e07b40a8)

When deactivating Carnot:
![image](https://github.com/MTrab/energidataservice/assets/11716346/5493499f-b838-4a3b-b324-09128cda3cb5)
