### ISSUE TITLE
Error when lading integration

### ISSUE THREAD

**Issue by hauard** [MTrab/energidataservice#372]
### Describe the issue

Getting error on HA startup:
Logger: homeassistant.setup
Source: setup.py:209

Setup failed for custom integration energidataservice: Requirements for energidataservice not found: ['async-retrying-ng==0.1.1'].

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

None

### Anything in the logs that might be useful for us?

```txt
Setup failed for custom integration energidataservice: Requirements for energidataservice not found: ['async-retrying-ng==0.1.1'].
```

**Comment by MTrab** [comment]
Update to latest version
