### ISSUE TITLE
Fixed cost no longer included after upgrade to HASS 2023.9.3

### ISSUE THREAD

**Issue by PMPoulsen** [MTrab/energidataservice#374]
### Describe the issue

Data shown do no longer include the fixed costs after I upgraded HASS to 2023.9.3.
Before the upgrade everything was fine, now it just shows raw Nordpool data.

I an having Elektrus (kronborg el) as fixed cost, and have so far provided correct additions.

P.S. there are coming changes in tarrifs from Energinet, will they be included automatically or will it require an update of the add-on?

### What version of Home Assistant Core has the issue?

2023.9.3

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

let me kno if this is needed

**Comment by MTrab** [comment]
Please provide all required information!

**Comment by PMPoulsen** [comment]
[config_entry-energidataservice-5e13f6e6fb97b3676370c039bb25368a.json.txt](https://github.com/MTrab/energidataservice/files/12749447/config_entry-energidataservice-5e13f6e6fb97b3676370c039bb25368a.json.txt)
Hope this is what you need, if you need more please let me know

**Comment by PMPoulsen** [comment]
![Skærmbillede 2023-09-28 144217](https://github.com/MTrab/energidataservice/assets/46517931/2b9e3f17-bce1-4090-bf50-b44d067f315a)
![Skærmbillede 2023-09-28 162400](https://github.com/MTrab/energidataservice/assets/46517931/dc875033-65cc-4274-af4d-bd8917c4c4f3)

The data shown in the graph (your example code) and for the sensor (see attached pictures) no longer includes the fixed transmission costs, it only shows the nordpool raw price, hence being too low. This has changed since i upgraded to 2023.9.3 before (2023.9.2) everything was shown fine.

**Comment by MTrab** [comment]
Must be local at your end - just setup an instance with your settings, and it checks out with elspotpris.dk

**Comment by PMPoulsen** [comment]
I just tried to remove the entity and installed it again (not removing the HACS component), and now it is back with correct data.
So are there any chance that the upgrade to 2023.9.3 can have overwritten some config parameters?

**Comment by MTrab** [comment]
No, the integration cannot change config parameters witout you doing something active in configuration

**Comment by PMPoulsen** [comment]
Strange, I did not change anything in the service. 

Anyway I get correct data again, and know the workaround if this happens again.

Thanks

**Comment by PMPoulsen** [comment]
There seems to be something not working correctly after all.
Over night the fixed cost has been removed again and only showing the raw nordpool price.
I did perform a reload of the service and then everything was shown correctly again.

I still think this is related to the lates HASS update as I did not see this behaviour before the upgrade.

Can i provide additional debug information in any way?

**Comment by MTrab** [comment]
Still temptet to rule this an issue at your end, as I don't see this in any of the 3 instances I manage.

Don't the log show any errors?

**Comment by PMPoulsen** [comment]
And you may be right if I am the only one experiencing this.

There are actually errors in the log (didn't check before you asked):

ClientResponseError -> Attempts (5) are over for <function Connector.async_call_api at 0xffffbb42a020>
00.12.48 – (ADVARSEL) Energi Data Service (brugerdefineret integration) - beskeden forekom først kl. 28. september 2023 kl. 00.12.16 og ses 2 gange
Error during API request: 500, message='Internal Server Error', url=URL('https://api.energidataservice.dk/dataset/DatahubPricelist?filter=%7B%22chargetypecode%22:+%5B%226000091%22%5D,%22gln_number%22:+%5B%225790000836239%22%5D%7D&sort=ValidFrom+desc&limit=500')
00.12.48 – (FEJL) Energi Data Service (brugerdefineret integration) - beskeden forekom først kl. 27. september 2023 kl. 00.01.06 og ses 11 gange

I don't know if this is helpful, however this is happening in the middle of the night

**Comment by PMPoulsen** [comment]
there were one more:

Retry attempts exceeded for tariffs request.
00.12.48 – (FEJL) Energi Data Service (brugerdefineret integration) - beskeden forekom først kl. 28. september 2023 kl. 00.12.16 og ses 2 gange

**Comment by MTrab** [comment]
At least that indicates an server error at Energi Data Service. Not sure if I can do much about that, other than raise the number of retries to fetch the tariffs.

**Comment by PMPoulsen** [comment]
perhaps the service is busy aground this time of night and a retry should be postpones e.g. 10 minutes.

Lets see if an increased retry count will solve this.

Closing this again, as the workarround is simpel now, just reload the service.

Thanks
