### ISSUE TITLE
tomorrow_valid = false | but prices are shows in entity.

### ISSUE THREAD

**Issue by Symbiot78** [MTrab/energidataservice#394]
### Describe the issue

not sure if this is just as it should be but the attributes for tomorrow are always false/unknown - even though the prices appear in the entity.
Like this:

![image](https://github.com/MTrab/energidataservice/assets/3314249/5d4534b3-e592-41ad-840b-f2c2e2d9ed53)

I've never seen the 'tomorrow' attributes work - but maybe i'm just doing something wrong?

### What version of Home Assistant Core has the issue?

any - but right now it's 2023.11.0

### What was the last working version of Home Assistant Core?

never

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[config_entry-energidataservice-15512cfd314e1340bd1d11848d4ad635.json.txt](https://github.com/MTrab/energidataservice/files/13256205/config_entry-energidataservice-15512cfd314e1340bd1d11848d4ad635.json.txt)

### Anything in the logs that might be useful for us?

```txt
no :(
```

**Comment by Symbiot78** [comment]
![image](https://github.com/MTrab/energidataservice/assets/3314249/333f9631-a673-4a2e-8440-c7fafeebe17f)

**Comment by Symbiot78** [comment]
... or does the "forecast" not have anything to do with the tomorrow attribute(s) ?

**Comment by MTrab** [comment]
According to your dataset there is no data in the tomorrow attributes.
The forecast has nothing to do with today or tomorrow datasets.

Remember the tomorrow dataset isn't available until ~14.00 DST

**Comment by Symbiot78** [comment]
allright - that makes sense and I don't know why I missed that data does flow after 14DST
