### ISSUE TITLE
Additional cost for Andel Energi TimeEnergi

### ISSUE THREAD

**Issue by karazzi** [MTrab/energidataservice#398]
### Describe the issue

It seems the additional cost for Andel Energi TimeEnergi should be {{0.141|float}}
At least that is the value that makes my apex chart match the values I see in the Andel iOS app :)

### What version of Home Assistant Core has the issue?

core-2023.11.1

### What type of installation are you running?

Home Assistant Container

### Diagnostics information

d

**Comment by MTrab** [comment]
And does the Andel app take tariffs into account - the value you mention doesn't match what I can see at https://stromligning.dk/ (not saying that is correct either, as these values a manual findings)

**Comment by karazzi** [comment]
The Andel app has a toggle to include transport and tarrifs. I was not able to find the value in writing but I managed to match prices over a 24 hour period

**Comment by MTrab** [comment]
I think something is off - according to Andel Energi webpage, the additional cost shoud be 0.108 (135 øre - vat)

**Comment by MTrab** [comment]
0.132 is the correct value for TimeEnergi - fixed in the wiki
