### ISSUE TITLE
Value is "Unknown" if restarted between 00:00 and 01:00 CET

### ISSUE THREAD

**Issue by FrederikNS** [MTrab/energidataservice#400]
### Describe the issue

I recently installed the addon and it works very well, but I notice that if I restart Home-Assistant (or reload this plugin) between 00:00 and 01:00 CET, then the value of the entity becomes "Unknown". It also doesn't recover by itself when the clock passes 01:00, but if I reload/restart after 01:00, then the value populates correctly and shows the cost again.

### What version of Home Assistant Core has the issue?

core-2023.11.1

### What type of installation are you running?

Home Assistant Container

### Diagnostics information

None

### Anything in the logs that might be useful for us?

```txt
No, unfortunately
```

**Comment by jladefoged** [comment]
I cursed a bit over this last night until I found this issue and can confirm it.

**Comment by MTrab** [comment]
Could this be the same as #447 ?
