### ISSUE TITLE
[FR]: Using [Input_number] as data for the "additional cost" template

### ISSUE THREAD

**Issue by tobenski** [MTrab/energidataservice#407]
### Describe the feature you wish to make a request for

It would be very nice to be able to use som input numbers for the "additional cost" template.

That way i would be possibel to change the cost template without having to reconfigere the integration.

```
{% set costs = {
    "n1_indfoedningstarif": input_number.n1_indfoedningstarif,
    "energinet_indfoedningstarif": input_number.energinet_indfoedningstarif,
    "energinet_balancetarif": input_number.energinets_balancetarif,
    "vindstoed_balancetarif": input_number.vindstoed_balancetarif
} %}
{{ 0 -  costs.n1_indfoedningstarif - costs.energinet_indfoedningstarif - costs.energinet_balancetarif - costs.vindstoed_balancetarif  | float }}
```

### Describe alternatives you've considered

i know i can just update the template by reconfiguring the integration

### Additional context

I'm using the integration to track my solar sell price (after additional costs)

**Comment by MTrab** [comment]
It's normal Jinja2 syntax, so you could refer to your input numbers by ie `{{ state('input_number.test') }}` just as in any other Home Assistant template
