### ISSUE TITLE
Commercial prices (no tax and VAT) and NRGI as service provider

### ISSUE THREAD

**Issue by Nooobiecake** [MTrab/energidataservice#411]
### Describe the feature you wish to make a request for

Would like this implemented

At 19:00 today. when i use Konstant as provider i get 2.03 DKK but my price is actually 0.50 DKK

Also my provider is NRGI.dk but in Konstant's supply area.

**Comment by MTrab** [comment]
And what is it you are requesting?

If you have configured the integration correct, then the prices are also correct 🤷🏼‍♀️
It's fetched from the central datahub

**Comment by Nooobiecake** [comment]
Den tager vi lige på dansk

NRGI er ikke umiddelbart på energi data service. 
Jeg kan ikke umiddelbart vælge at vise prisen uden afgifter. Ikke bare moms. Jeg ønsker brutto prisen vises.

Er der en måde at gøre det på?

**Comment by MTrab** [comment]
NRGi er ikke kabel operatør, så vidt jeg ved, derfor er de ikke på listen.

Hvis ikke du vil have tariffer, så lader du bare være med at sætte flueben i at hente tariffer - så får du den rå spotpris

**Comment by Nooobiecake** [comment]
Ahh tak! Det prøver jeg
