### ISSUE TITLE
Subscription template price for "Clever Power" is incorrect

### ISSUE THREAD

**Issue by jonaskp** [MTrab/energidataservice#412]
### Describe the issue

The template on the page: https://github.com/MTrab/energidataservice/wiki/How-to-add-costs-of-subscription-and-delivery%3F

Shows Clever Power as "0.008".
**The current price of Clever Power is "0.0154" (according to the agreements I've recieved from them when signing up in December, and the Elspotpris.dk webpage)**

(Not sure if this is the right place, but the page above just says "report it").

### What version of Home Assistant Core has the issue?

N/A

### What was the last working version of Home Assistant Core?

N/A

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

N/A (issue related to wiki, not home assistant installation"

**Comment by MTrab** [comment]
Thank you for reporting - WiKi have been updated
