### ISSUE TITLE
[FR]: EDS reload when sensor reached certain value

### ISSUE THREAD

**Issue by tk-gns** [MTrab/energidataservice#418]
### Describe the feature you wish to make a request for

When following the guide at Wiki for reduced electrical fee. It specifies to have a sensor which monitors the monthly usage, so EDS can reduce the electrical fee after 334kWh.

After the sensor reaches the specified level. The electrical fee is not reduced before EDS is reloaded.

### Describe alternatives you've considered

Currently i solve this with an automation which monitors the sensor and then reloads EDS.

**Comment by MTrab** [comment]
Currently the prices are only calculated on midnight and when tomorrow gets available in the API endpoint.

I think the prices should be recalculated on an hourly basis, to reflect a more correct price.
I know the threshold would be reached between the hourly calculations, but I think to keep the compatibility with other components this might be the best compromise available.
