### ISSUE TITLE
WIKI: Additional Cost, EWII Grøn Indkøbspris

### ISSUE THREAD

**Issue by mm98** [MTrab/energidataservice#421]
### Describe the issue

> NOTE! This list is manually maintained, and if one of the templates are no longer correct, please do report this.

Hi,

This isn't really a bug or an issue. More of a change for 2024. I've previously defined `{{ 0.03 | float(0) }}` as additional cost for `EWII Grøn Indkøbspris` (West). I've manually tried to adjust it, to make it partially match what is reported on [elspotpris.dk](https://elspotpris.dk/) as of 2024, which is roughly `{{ 0.05 | float(0) }}`. This is not a 100% match tough. So my question is, how or where to a find the exact value?

### What version of Home Assistant Core has the issue?

core-2024.1.2

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

None ...

### Anything in the logs that might be useful for us?

```txt
None ...
```

### Additional information

WIFI link is https://github.com/MTrab/energidataservice/wiki/How-to-add-costs-of-subscription-and-delivery%3F#additional-costs-template-when-using-tariff-data

**Comment by MTrab** [comment]
You'll most probably find it on your bill, or on the webpage for the product you have

**Comment by mm98** [comment]
Thanks @MTrab i'll look trough my papers!
