### ISSUE TITLE
Priser NOK/Oslo er fejl

### ISSUE THREAD

**Issue by bse4792** [MTrab/energidataservice#425]
### Describe the issue

Hej.

Jeg har vedlagt dump af dianose samt billed ag priser fra Nord Pool. håber du kan se/gennemskue feilen.
![Screenshot 2024-01-21 21 30 48](https://github.com/MTrab/energidataservice/assets/29598723/c594ddaa-b294-4a87-9167-f2493684434a)

### What version of Home Assistant Core has the issue?

2024.1.4

### What was the last working version of Home Assistant Core?

ved ikke

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[config_entry-energidataservice-f0956bc2c4ae7e1d5bd38e6228015433.json (1).txt](https://github.com/MTrab/energidataservice/files/14002746/config_entry-energidataservice-f0956bc2c4ae7e1d5bd38e6228015433.json.1.txt)

**Comment by MTrab** [comment]
Hvilken side henter du priserne som på billedet fra?

Priserne fra integrationen hentes ved Nord Pool

**Comment by bse4792** [comment]
Det er direkte fra nord pool hjemmeside, jeg har snippet fra, jeg har også nord pool integration som giver korrekte priser, men den har ikke mulighed for at ligge ind ekstra abonnement priser

**Comment by bse4792** [comment]
![Screenshot 2024-01-24 22 31 33](https://github.com/MTrab/energidataservice/assets/29598723/8e568119-b1d7-4e64-a759-7659a5abad72)
![Screenshot 2024-01-24 22 31 05](https://github.com/MTrab/energidataservice/assets/29598723/f6192d35-d3c2-499a-873c-8cf3a6ad8af3)
lidt screendumps fra både energi service og nord pool plugins

**Comment by MTrab** [comment]
Kan det være i konverteringen af EUR->NOK?
Priserne trækkes ind i EUR og omregnes så med den aktuelle dagskurs lokalt af EDS på din maskine.

**Comment by bse4792** [comment]
det kan være det er det, men hvorfor lage en konvertering fra €->NOK når nordpool levere priser direkte i NOK

Jeg er godt klar over det øre vi snakker, men med priser på som har været højt oppe, så har øre også en betydning med strømforbrug på ca 24000-26000kWh/år.

**Comment by MTrab** [comment]
Fordi ved at hente i EUR kan vi simplificere API kaldet.
Det er alligevel ikke alle valutaer der understøttes direkte i API.
Desuden er denne integration oprindeligt bygget til Energi Data Service APIet, men har senere fået tilføjet Nordpool som fallback.
Energi Data Service leverer kun priser i DKK eller EUR

**Comment by bse4792** [comment]
Det er helt ok, men så bør du jo lukke ned for andre valutaer i denne plugin eller evt se hvordan https://github.com/custom-components/nordpool/ har lavet deres api kald, jeg forstår det du skriver til fulde, men jeg kan egentlig godt lide at man har mulighed for evt ekstra udgifter til leverandøren, som nord pool plugin ikke har

**Comment by MTrab** [comment]
Den brugte valuta er den du har angivet i din Home Assistant configuration

**Comment by perfrank** [comment]
Ovenstående forklarer hvorfor jeg ikke kan få overensstemmelse mellem Nord Pool og SDS.
Jeg bor i DK, men har også hus i Sverige. Styre energi begge steder med HA. Serveren står i DK.

At valuta hentes i HA betyder, som jeg opfatter ovenstående, at jeg skal omregne svenske priser (tariffer/afgifter) til DKK for at få slutprisen til at passe. Er det rigtigt forstået? 

Og er der en måde at undgå dette, således at jeg regner i DKK i DK og SKr i S?

**Comment by perfrank** [comment]
Tak for meget hurtigt svar:)

Så jeg skal omregne værdierne i "Template for additional cost" til DKK for
at prisen bliver rigtig (i DKK)?

Det betyder så, at jeg skal korrigere værdierne, når kursen ændrer sig.
Lidt bøvlet men ok.
Jeg har i alle tilfælde fået forklaringen på, at jeg ikke kunne få tallene
til at stemme. Det var måske ikke den smarteste beslutning at beregne alt i
lokal valuta, inc. moms.

Med venlig hilsen / best regards

Per Frank-Hansen
Søvej 3
2665 Vallensbæk Strand
+45 20837692


Den ons. 31. jan. 2024 kl. 12.26 skrev Malene Trab ***@***.***
