### ISSUE TITLE
[FR]: With auto tariff enabled, don't always include Danish 'elafgift'

### ISSUE THREAD

**Issue by mikkel75** [MTrab/energidataservice#438]
### Describe the feature you wish to make a request for

It seems like when auto download of tariffs is enabled, the prices automatically also include 'elafgift' (when in Denmark).
Would it be possible to have 'elafgift' as an option to include or not?

**Comment by MTrab** [comment]
Can be subtracted using the additional cost template and the variable mentioned in the wiki (https://github.com/MTrab/energidataservice/wiki/How-to-add-costs-of-subscription-and-delivery%3F#extra-variables-that-can-be-used-in-templates)
