### ISSUE TITLE
[FR]: Description of having reduced electrical fee

### ISSUE THREAD

**Issue by DK-MGO** [MTrab/energidataservice#440]
### Describe the feature you wish to make a request for

Hello,

Would it be possible for someone to write a small how-to for combining:

https://github.com/MTrab/energidataservice/wiki/How-to-add-costs-of-subscription-and-delivery%3F#additional-costs-template-when-using-tariff-data
and
https://github.com/MTrab/energidataservice/wiki/Template-example-for-using-reduced-electrical-fee-in-Denmark,-using-over-4000kWh-pr.-year
I guess the first is entered into the setup UI for Energi Data Service, but then how do I use the second?

Thank you!

### Additional context

I update the template from the first URL to fit with my electricity provider:
`{% set costs = {
"elafgift": 0.763,
"nettarif_lav": 0.1636,
"nettarif_spids": 0.4537,
"abonnement_net": 0.09425,
"eltillaeg_ellev": 0.07,
"abonnement_ellev": 0.725
} %}

{% if now().month >= 10 or now().month < 4 %}
{% if now().hour >= 17 and now().hour < 20 %}
{{
costs.elafgift +
costs.nettarif_spids +
costs.abonnement_net +
costs.eltillaeg_ellev +
costs.abonnement_ellev
}}
{% else %}
{{
costs.elafgift +
costs.nettarif_lav +
costs.abonnement_net +
costs.eltillaeg_ellev +
costs.abonnement_ellev
}}
{% endif %}
{% else %}
{{
costs.elafgift +
costs.nettarif_lav +
costs.abonnement_net +
costs.eltillaeg_ellev +
costs.abonnement_ellev
}}
{% endif %}`

and paste that in here:
![image](https://github.com/MTrab/energidataservice/assets/101643418/61d3b803-2a07-4c6c-9d85-4a7f2e73064b)

But what do I do with this?
`{% if states("sensor.hovedforsyning_energy_total_current_month") | float > 334 %}
{% set reduction = ( el_afgift - 0.008 ) | float(0) %}
{% endif %}`

**Comment by MTrab** [comment]
What you request is already mentioned in the wiki
