### ISSUE TITLE
Wiki: Proposal to update EWII additional costs, to reflect 2024 prices and products

### ISSUE THREAD

**Issue by Rosiak** [MTrab/energidataservice#441]
### Describe the issue

Hi,

EWII have updated their prices and products for 2024, thus it would be great to have this reflected in here.

**Page**  
https://github.com/MTrab/energidataservice/wiki/How-to-add-costs-of-subscription-and-delivery%3F#additional-costs-template-when-using-tariff-data

**Current**
Subscription | Template
-- | --
EWII Grøn Indkøbspris | {{0.03\|float(0)}}

**Proposed update**
Subscription | Template
-- | --
EWII - Timepris | {{0.03\|float(0)}}  
EWII - Grøn Timepris | {{0.078\|float(0)}}

**Supporting material**
https://www.ewii.dk/privat/el/timepris-el/
https://www.ewii.dk/privat/el/groen-timepris/

```
Med Timepris betaler du den variable timepris på den nordiske elbørs Nordpool og et fast spottillæg på 3,75 øre pr. kWh.
```

```
Med Grøn Timepris vælger du en gennemskuelig og fremtidssikret elaftale, hvor du betaler den variable timepris på den nordiske elbørs Nordpool plus et fast timetillæg på 3,75 øre pr. kWh og et tillæg for grøn strøm på 6 øre pr. kWh. Det samlede tillæg udgør således 9,75 øre pr. kWh.
```

```
Alle oplyste priser er inkl. moms.
```

Let me know if I missed something or if you need more clarity - thanks!

### What version of Home Assistant Core has the issue?

n/a

### What was the last working version of Home Assistant Core?

n/a

### What type of installation are you running?

Home Assistant Container

### Diagnostics information

n/a

**Comment by MTrab** [comment]
Fixed
