### ISSUE TITLE
Fails, recalculation of prices every hour #451

### ISSUE THREAD

**Issue by mm98** [MTrab/energidataservice#452]
### Describe the issue

On every hourly reload (from #451), the prices are incorrect (lower) until EDS is manually reloaded.

Before reload:
![image](https://github.com/MTrab/energidataservice/assets/992714/9040991e-cf52-482d-8c5d-911f622d7a48)

After reload:
![image](https://github.com/MTrab/energidataservice/assets/992714/95651acd-14c9-4fb3-bc49-c11fbc9151d7)

### What version of Home Assistant Core has the issue?

2024.2.5

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_energidataservice_2024-02-28T16-10-24.900Z.log](https://github.com/MTrab/energidataservice/files/14436788/home-assistant_energidataservice_2024-02-28T16-10-24.900Z.log)

### Anything in the logs that might be useful for us?

```txt
Only occurs on the internal hourly reload. Almost looks like it is missing the tariffs (just a guess).
```

**Comment by MTrab** [comment]
Does this occur EVERY hour?
Just ran another test, and apparantly it works as supposed here.

**Comment by Waseh** [comment]
I'm seeing the same thing

**Comment by erviem99** [comment]
I can confirm. I just broke here again at 13.00.

**Comment by yoali11** [comment]
I can also confirm this bug. I started charging my car due to the seemingly low electricity prices and noticed only later by the amount charged that something was off 😅

**Comment by MTrab** [comment]
I have pulled v1.5.0 so no further users install or upgrade to that version.
Will see if I can recreate and create a fix

**Comment by mm98** [comment]
> Will see if I can recreate and create a fix

Just a small note. I noticed the bug on the first hour (after update). I `Enabled debug logging` just before the second run, since I almost was certain it would happen again. Meaning the debug log i added, should be from hourly update with incorrect data. Don't know if you can see anything from this or use it at all.

**Comment by mm98** [comment]
I would reopen this issue. The main electricity prices are correct now, but the forecast data (carnot) has the same bug.
