### ISSUE TITLE
Wrong price reported (DK1)

### ISSUE THREAD

**Issue by erviem99** [MTrab/energidataservice#454]
### Describe the issue

After latest upgrade today the prices for DK1 has suddenly changed

today: 1.244, 1.244, 1.244, 1.244, 1.244, 1.244, 1.412, 1.412, 1.413, 1.413, 1.413, 1.413, 1.413, 1.413, 1.413, 1.413, 1.413, 1.919, 1.919, 1.919, 1.918, 1.413, 1.413, 1.413

This is not consistent with the prices in data.nordpoolgroup.com

### What version of Home Assistant Core has the issue?

2024.2.5

### What was the last working version of Home Assistant Core?

2024.2.4

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[energi data service.txt](https://github.com/MTrab/energidataservice/files/14446591/energi.data.service.txt)

**Comment by MTrab** [comment]
Duplicate og #452
