### ISSUE TITLE
[FR]: Make it work seamless with Node-Red Power Saver

### ISSUE THREAD

**Issue by alexthomsen** [MTrab/energidataservice#455]
### Describe the feature you wish to make a request for

Im using the power saver module for node-red. It will determine the cheapest hours and turn on devices configured. It´s currently working with nordpool data, but there are a small variable diff for the energi_data_service. Please implement the data like this: - start: '2024-02-29T00:00:00+01:00'
  end: '2024-02-29T01:00:00+01:00'
  value: 6.479

**Comment by MTrab** [comment]
Should be necessary with this change, as start is defined in every price set. End is just the start of the next, so the end info is redundant

**Comment by MTrab** [comment]
Also changing the attribute `price` to `value` would raise a pretty big breaking change for ALOT of users.

**Comment by Boss-man** [comment]
Maybe OP could make a request for the Power Saver developer to make it compatible with EDS.
