### ISSUE TITLE
Future price becomes pure tariffs after a while

### ISSUE THREAD

**Issue by wormiedk** [MTrab/energidataservice#461]
### Describe the issue

Right after the integration starts prices look ok but after a few minutes reduce to pure tariffs.

Just after restart of integration:
<img width="445" alt="Screenshot 2024-03-01 at 20 06 22" src="https://github.com/MTrab/energidataservice/assets/4417857/c1617ef8-50dc-4e50-8114-2c0902694e6f">

After a few minutes:
<img width="329" alt="Screenshot 2024-03-01 at 20 03 40" src="https://github.com/MTrab/energidataservice/assets/4417857/93479c5f-a4ac-4dfc-9cb9-4156ef76fc72">

### What version of Home Assistant Core has the issue?

2024.3.0b3

### What was the last working version of Home Assistant Core?

Unsure

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[config_entry-energidataservice-03d1d05472cb2004748385a872c4234d.json](https://github.com/MTrab/energidataservice/files/14465016/config_entry-energidataservice-03d1d05472cb2004748385a872c4234d.json)

**Comment by wormiedk** [comment]
Code for the apexcharts card
```
type: custom:apexcharts-card
apex_config:
  chart:
    height: 250px
  xaxis:
    labels:
      datetimeFormatter:
        hour: HH
experimental:
  color_threshold: true
graph_span: 18h
header:
  title: Elpriser pr. time (kr/kWh)
  show: true
span:
  start: hour
  offset: '-1h'
now:
  show: true
  label: Nu
yaxis:
  - min: ~1
    apex_config:
      tickAmount: 5
series:
  - entity: sensor.energi_data_service
    type: column
    data_generator: |
      var today = entity.attributes.raw_today.map((start, index) => {
        return [new Date(start["hour"]).getTime(), entity.attributes.raw_today[index]["price"]];
      });
      if (entity.attributes.tomorrow_valid) {
        var tomorrow = entity.attributes.raw_tomorrow.map((start, index) => {
          return [new Date(start["hour"]).getTime(), entity.attributes.raw_tomorrow[index]["price"]];
        });

        var data = today.concat(tomorrow);
      } else {
        var data = today
      }
      return data;
    float_precision: 2
    color_threshold:
      - value: 0
        color: green
      - value: 2
        color: orange
      - value: 3.5
        color: red
      - value: 5
        color: darkred

```

**Comment by mm98** [comment]
@wormiedk do you use the latest release `1.5.3`?

I can't see this problem or reproduce it at my end. There was a few bugs in `1.5.0` and `1.5.1`.

**Comment by MTrab** [comment]
Please update to the latest version, as that should fix the issue

**Comment by MTrab** [comment]
Did it fix the issue, updating to the latest version?

**Comment by wormiedk** [comment]
Yes for some reason I had to open hacs before the update became visible. After updating the problem went away.
