### ISSUE TITLE
[FR]: Push low price variable if the price is the lowest of the day

### ISSUE THREAD

**Issue by Sleazified** [MTrab/energidataservice#47]
Hello. 

I would like the integration to deliver a variable which is true, if the price is within the x lowest hours of the day.

Eg. when the component is setup, you can put an setting with the requested number of hours of low price.

Like, if i wanted the 5 hours with the lowest price, it would be true in those 5 hours, and false the rest of the day.

Example: 
Electricty price - Hour of the day - Status of the variable
2.59 - 0 - Low_Price: False
2.51 - 1 - Low_Price: False
2.31 - 2 - Low_Price: True
2.32 - 3 - Low_Price: True
2.31 - 4 - Low_Price: True
2.59 - 5 - Low_Price: False
2.57 - 6 - Low_Price: False
2.65 - 7 - Low_Price: False
2.77 - 8 - Low_Price: False
2.81 - 9 - Low_Price: False
2.93 - 10 - Low_Price: False
2.88 - 11 - Low_Price: False
2.75 - 12 - Low_Price: False
2.11 - 13 - Low_Price: True
2.22 - 14 - Low_Price: True
2.63 - 15 - Low_Price: False
2.77 - 16 - Low_Price: False
2.98 - 17 - Low_Price: False
3.01 - 18 - Low_Price: False
3.11 - 19 - Low_Price: False
3.09 - 20 - Low_Price: False
3.15 - 21 - Low_Price: False
2.97 - 22 - Low_Price: False
2.88 - 23 - Low_Price: False

And of course, if i wanted the 10 hours with the lowest price of the day, i would put in 10 instead of 5 in the setup menu.

**Comment by MTrab** [comment]
Actually, excact such feature I'm already building ;) It'll take either an input_number helper entity with the length you want to look for or a static number of hours.

So just hang on - will be coming in the near future.

**Comment by MTrab** [comment]
Actually it's issue #35
