### ISSUE TITLE
Only 10 days of data available

### ISSUE THREAD

**Issue by vaibhavratnaparkhi** [MTrab/energidataservice#485]
### Describe the issue

Only data from the last 10 days is available in the integration. Can it be possible to store / access data for a longer duration - which can also be configured?

### What version of Home Assistant Core has the issue?

core-2024.4.4

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

None

### Anything in the logs that might be useful for us?

```txt
None
```

### Additional information

None

**Comment by MTrab** [comment]
Check your recorder settings, this is not an EDS issue
