### ISSUE TITLE
[FR]: Allow negative values in template

### ISSUE THREAD

**Issue by oz9els** [MTrab/energidataservice#505]
### Describe the feature you wish to make a request for

For price without Danish Elafgift one is not able to have template like: {{-0.761 |float}}
It could also be special rebates. 

### Describe alternatives you've considered

Allowing negative values in template

**Comment by MTrab** [comment]
It's a "bug" in the build in Jinja2 template renderer in Home Assistant, and not as such a bug or missing feature in this integration:

https://github.com/MTrab/energidataservice/issues/293#issuecomment-1596954030
