### ISSUE TITLE
v1.5.7 is incompatible with HA 2024.5.5 and older

### ISSUE THREAD

**Issue by DarkFox** [MTrab/energidataservice#515]
### Describe the issue

The integration fails to load on HA 2024.5.5 (and most likely older versions) due to the new timezone code.

It should be restricted to versions 2024.6.0 and newer.

Side note: The integration logs the email and API key to the diagnostic log, that you then ask people to upload and make available publicly... That's not very nice.

### What version of Home Assistant Core has the issue?

core-2024.5.5

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_energidataservice_2024-06-12T22-44-32.567Z.log](https://github.com/user-attachments/files/15811696/home-assistant_energidataservice_2024-06-12T22-44-32.567Z.log)

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.config_entries
Kilde: config_entries.py:584
Første forekomst: 12. juni 2024 kl. 23.20.10 (3 forekomster)
Senest logget: 00.44.29

Error setting up entry Energi Data Service for energidataservice
Error setting up entry Energi Data Service Spotpriser for energidataservice
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 584, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/__init__.py", line 54, in async_setup_entry
    result = await _setup(hass, entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/__init__.py", line 89, in _setup
    api = APIConnector(hass, entry, rand_min, rand_sec)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/api.py", line 90, in __init__
    self._tz = dt_util.get_default_time_zone()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.util.dt' has no attribute 'get_default_time_zone'. Did you mean: 'set_default_time_zone'?
```

**Comment by Strit** [comment]
The requirements.txt file does state it requires home assistant 2024.6.2 since https://github.com/MTrab/energidataservice/commit/266c43dba40ecb16b3806ce12daafe7dc42edc2a. So this feels like it's working as intended...

**Comment by MTrab** [comment]
HACS requirements have been updated to reflect this
