### ISSUE TITLE
[FR]: Add N1/Norlys PuljeEl prices

### ISSUE THREAD

**Issue by Strit** [MTrab/energidataservice#521]
### Describe the feature you wish to make a request for

I think it would be nice to have an entity that just has the "fixed" price of the PuljeEl subsctiption from N1/Norlys, since many have that subscription.

### Describe alternatives you've considered

I am currently using a helper in Home Assistant, where I have to update the price manually.

**Comment by MTrab** [comment]
And the fixed price option can't cover this?

**Comment by Strit** [comment]
Well, the price changes every 3 months, so I would still have to manually change it then, right?

**Comment by MTrab** [comment]
Correct - that's the only option if using fixed prices.

**Comment by Strit** [comment]
I guess I just hoped there was a way to pull the quarterly price from the supplier automaticly instead. But if that is not possible then you can close this request.

**Comment by MTrab** [comment]
As well as every other supplier is a manual entry, this will be as well. There is no central API to pull this information from
