### ISSUE TITLE
Unable to load pricelist

### ISSUE THREAD

**Issue by motionist** [MTrab/energidataservice#540]
### Describe the issue

As of today, the pricelist including tariffs cannot be loaded. 
Pricelist without tariffs and taxes loads without problems

### What version of Home Assistant Core has the issue?

2024.7.3

### What was the last working version of Home Assistant Core?

2024.7.2

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

Unable to obtain log 

### Anything in the logs that might be useful for us?

```txt
This error originated from a custom integration.

Logger: custom_components.energidataservice.tariffs.energidataservice
Source: custom_components/energidataservice/tariffs/energidataservice/__init__.py:209
integration: Energi Data Service (documentation, issues)
First occurred: 04:34:17 (6 occurrences)
Last logged: 08:33:36

Error during API request: 500, message='Internal Server Error', url=URL('https://api.energidataservice.dk/dataset/DatahubPricelist?filter=%7B%22Note%22:%5B%22Elafgift%22,%22Systemtarif%22,%22Transmissions+nettarif%22%5D%7D&limit=500') de
```

### Additional information

There has been issues with eds since 2024.7 in general, however core data could be read 
Although some data was not available e.g long forecast seemed to be in a format where some information was unreadable

**Comment by fribse** [comment]
I can confirm, I see the exact same behaviour

**Comment by MTrab** [comment]
Internal server error is at the API end. Nothing I can do
