### ISSUE TITLE
Energy data service does not boot

### ISSUE THREAD

**Issue by ThomasGNielsen** [MTrab/energidataservice#541]
### Describe the issue

As og today, the integration will not start when Home Assistant is rebooted. It just say “configuration did not succeed”. 

> I have not changed anything and have made no resent updates.
>  I have the latest version of the integration 1.5.8.

Hope something can be done as I use the integration to charge my 🚗 

### What version of Home Assistant Core has the issue?

2024.7.1

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

No logbook entry can be found. The integration does simply not start.

**Comment by MTrab** [comment]
Same as #540
