### ISSUE TITLE
Ingen pris kl 12 i dag

### ISSUE THREAD

**Issue by JBoye** [MTrab/energidataservice#55]
Jeg ved ikke lige hvordan det kan opstå, men jeg mangler simpelthen en pris mellem kl 11 og 13 

![image](https://user-images.githubusercontent.com/5902488/170458263-2811eeff-577d-4fe9-847b-08653ca5a562.png)

V0.2.0 og HA 2022.5.5 - Jeg har genstartet alt 2 gange

**Comment by MTrab** [comment]
Same - sad og kiggede lidt på det igår, men kunne ikke lige lure hvad det kunne være.

**Comment by larserhardsen** [comment]
Kan det ikke tænkes at det er fordi spotprisen er 0,0kr?

**Comment by MTrab** [comment]
Jo, men hvis man har additional costs på, så burde de jo stadig være der. Ellers er der noget galt i formlen 🤷🏼‍♀️

**Comment by JBoye** [comment]
Det lyder sandsynligt at der er et nullcheck et sted som fjerner den

**Comment by MTrab** [comment]
Må prøve at lave nogle tests på det.
Men tak for info, tænkte at det nok bare var min der var lidt dum, idet jeg havde rodet med en del tests af ny Landroid integration ;)

**Comment by MTrab** [comment]
Idag er det så kl 15 der skipper - kan se i dataset at prisen er 0.0EUR/MWh ;)
Men jeg har fundet fejlen og får en updatering ud i løbet af formiddagen.
