### ISSUE TITLE
Issue: Wiki article about reduced electrical fee in Denmark

### ISSUE THREAD

**Issue by Peethiplatsch** [MTrab/energidataservice#552]
### Describe the issue

The template used within the Wiki article "[Template example for using reduced electrical fee in Denmark, using over 4000kWh pr. year](https://github.com/MTrab/energidataservice/wiki/Template-example-for-using-reduced-electrical-fee-in-Denmark,-using-over-4000kWh-pr.-year)" seems incorrect for me. Maybe I see it wrong, but as I understand it it reduces the elafgivt by 0,008 and not to 0,008 DKK. As far as I understood, with my limited danish, as seen in the NRGi example [Få reduceret din elafgift](https://nrgi.dk/privat/stroem/kundeservice/betaling/faa-reduceret-din-elafgift/) the afgift is 0,01 DKK which is without moms 0,008. Maybe I am too stupid, but I don't find where to change the article, but even then, I am not sure if I would do it correctly. But my suggestion is, if we cannot just set the elafgift variable to 0,008. Not sure how this interferes with the automatic tarif data.

Cheers
Peter

### What version of Home Assistant Core has the issue?

core-2024.8.0

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

Just an issue with the wiki article, nothing bad :)

**Comment by MTrab** [comment]
I don't even understand what you mean by this issue, sorry.
Could you try and explain in another way?

**Comment by Peethiplatsch** [comment]
Hej, 

hahahahahahahaha. Damnit.
That happens when you do the stuff in the middle of the night.

i just typed what I meant to explain it further and I think it is correct what you did.

here what I stsrted to write.
—————————————————
in the code for the template:

{% if states("sensor.hovedforsyning_energy_total_current_month") | float > 334 %}   
  {% set reduction = ( el_afgift - 0.008 ) | float(0) %}
{% endif %}

{{ 0.012 - reduction | default(0) | float(0) }}

you are referring to the variable(?) “elafgift“ and you subtract 0,008 from it. That would mean that the elafgift variable is 0,761 - 0,008 = 0,753 but it should be 0,008.
Since that is stored within the variable “reduction“ the last calculation is 0,012 - 0,753….

——————————————————

There it struck me because you need to reduce the difference since the elafgift is already part of it 😅
If thats correct, this can be closed.


Many thanks for your response and have a nice weekend later.

**Comment by MTrab** [comment]
You are exactly correct
