### ISSUE TITLE
Integration refuses to start in 2024.8

### ISSUE THREAD

**Issue by Puppetmaster91** [MTrab/energidataservice#554]
### Describe the issue

You probably have an update ready, if thats the case just solve this one.

I receive this error after updating to 2024.8.0
Error during API request: 500, message='Internal Server Error', url=URL('https://api.energidataservice.dk/dataset/DatahubPricelist?filter=%7B%22Note%22:%5B%22Elafgift%22,%22Systemtarif%22,%22Transmissions+nettarif%22%5D%7D&limit=500')

### What version of Home Assistant Core has the issue?

2024.8.0

### What was the last working version of Home Assistant Core?

2024.7.4

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_energidataservice_2024-08-08T05-36-52.943Z.log](https://github.com/user-attachments/files/16538284/home-assistant_energidataservice_2024-08-08T05-36-52.943Z.log)

**Comment by MTrab** [comment]
Server error 500 is an API endpoint error and nothing I can do to fix it
