### ISSUE TITLE
Help needed with additional costs

### ISSUE THREAD

**Issue by stauffenberg2020** [MTrab/energidataservice#578]
### Describe the issue

I basically want to dot he following using this HA add on.

`[max(nordpool_price_without_VAT, 0) + 0.2515]*1.37`

Can you please help me how do I add this to the HA template for additional costs?

### What version of Home Assistant Core has the issue?

2024.8.3

### What was the last working version of Home Assistant Core?

2024.8.3

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

Its not exactly a bug

**Comment by MTrab** [comment]
I have no idea what you are trying to accomplish, maybe some of the other users in here can help

**Comment by MTrab** [comment]
I still don't know what you are trying to achieve,  so I cannot help.
It's basic Jinja templating, so if it works in the developer tools it should work in the integration

**Comment by MTrab** [comment]
I think you'd find more help in the Home Assistant group rather than here

**Comment by MTrab** [comment]
I'm no wizard to those templates, hence my answer.
It's not (as I see it) a bug nor a feature request

**Comment by mm98** [comment]
> {{ (max(current_price,0) + 0.2515) * 1.37 }}

This can be done by YAML template:

`{{ ((current_price if current_price > 0 else 0) + 0.2515) * 1.37 }}`

**Comment by mm98** [comment]
> > {{ (([current_price, 0] | max) + 0.2515) * 1.37 }}
> 
> Thanks @mm98 . Can you help me where exactly I should add/update this)

This isn't something you can define in EDS and shouldn't be 😉

There is no way for me to help with this. The user case and requirements is different per user. I would suggest you take a look at this tutorial video, which describes what `Templates` are and now to create them in HA.

https://www.youtube.com/watch?v=m1aqyX6LXlo
