### ISSUE TITLE
Fetch from api.energidataservice.dk:443 fails

### ISSUE THREAD

**Issue by ferreusDK** [MTrab/energidataservice#581]
### Describe the issue

First of alle really appriciate this integration, very nice work.

It stopped being able to fetch data from te api just recently. 

**However i encounter the following issue:**
This error originated from a custom integration.

Logger: custom_components.energidataservice.tariffs.energidataservice
Source: custom_components/energidataservice/tariffs/energidataservice/__init__.py:209
integration: Energi Data Service (documentation, issues)
First occurred: 5 September 2024 at 08:24:30 (10 occurrences)
Last logged: 08:01:28

Error during API request: Cannot connect to host api.energidataservice.dk:443 ssl:default [None]

### What version of Home Assistant Core has the issue?

2024.6.1

### What type of installation are you running?

Home Assistant Container

### Diagnostics information

[home-assistant_energidataservice_2024-09-06T06-22-47.232Z.log](https://github.com/user-attachments/files/16903765/home-assistant_energidataservice_2024-09-06T06-22-47.232Z.log)

### Anything in the logs that might be useful for us?

```txt
HTTPSConnectionPool(host='api.eloverblik.dk', port=443): Max retries exceeded with url: /CustomerApi/api/Token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fff5df71820>: Failed to establish a new connection: [Errno -3] Try again'))

Error during API request: Cannot connect to host api.energidataservice.dk:443 ssl:default [None]
```

**Comment by MTrab** [comment]
Try reloading. 

Cannot do anything about API outages

**Comment by ferreusDK** [comment]
Ah okay.. so its the endpoint that is down?

**Comment by MTrab** [comment]
From the error, yes. But it's working from here though

**Comment by ferreusDK** [comment]
Which version of Core do are you running?

**Comment by ferreusDK** [comment]
Will try update it to latest and see if that resolves anything. .Thank you!

**Comment by ferreusDK** [comment]
Its resolved now. :)
