### ISSUE TITLE
Integrations fails in set up: "AttributeError: 'APIConnector' object has no attribute 'api'"

### ISSUE THREAD

**Issue by yoali11** [MTrab/energidataservice#585]
### Describe the issue

The integration fails to set up. The following error is shows in the log:

`AttributeError: 'APIConnector' object has no attribute 'api'`

### What version of Home Assistant Core has the issue?

core-2024.9.1

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_energidataservice_2024-09-10T16-12-25.551Z.log](https://github.com/user-attachments/files/16947817/home-assistant_energidataservice_2024-09-10T16-12-25.551Z.log)

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 4:41:44 pm (3 occurrences)
Last logged: 6:09:31 pm

Error setting up entry Energi Data Service for energidataservice
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/__init__.py", line 54, in async_setup_entry
    result = await _setup(hass, entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/__init__.py", line 185, in _setup
    await api.async_get_tariffs()
  File "/config/custom_components/energidataservice/api.py", line 291, in async_get_tariffs
    if self.api.status != 200:
       ^^^^^^^^
AttributeError: 'APIConnector' object has no attribute 'api'
```

**Comment by onrust** [comment]
I'm having exactly the same issue and error log after updating this integration to the latest version.

**Comment by MTrab** [comment]
Downgrade
