### ISSUE TITLE
Can't get data

### ISSUE THREAD

**Issue by handswork** [MTrab/energidataservice#588]
### Describe the issue

I updated to 1.5.12 and some hours later it stopped working

Tried to create a new one, no luck

### What version of Home Assistant Core has the issue?

2024.9.1

### What was the last working version of Home Assistant Core?

2024.9.1

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_energidataservice_2024-09-11T11-04-39.405Z.log](https://github.com/user-attachments/files/16962645/home-assistant_energidataservice_2024-09-11T11-04-39.405Z.log)

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.config_entries
Kilde: config_entries.py:604
Første forekomst: 12.53.22 (3 forekomster)
Senest logget: 12.57.04

Error setting up entry uden_tariffer for energidataservice
Error setting up entry Strømpriser for energidataservice
Error setting up entry Test for energidataservice
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/__init__.py", line 54, in async_setup_entry
    result = await _setup(hass, entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/__init__.py", line 185, in _setup
    await api.async_get_tariffs()
  File "/config/custom_components/energidataservice/api.py", line 291, in async_get_tariffs
    if self.api.status != 200:
       ^^^^^^^^
AttributeError: 'APIConnector' object has no attribute 'api'
```

**Comment by mm98** [comment]
Version `1.5.12` has been redacted. Downgrade to latest version, which now is `1.5.11`.

https://github.com/MTrab/energidataservice/issues/585#issuecomment-2341433571

**Comment by MTrab** [comment]
Version 1.5.12 no longer exists,  latest version is 1.5.11
