### ISSUE TITLE
[FR]: Reduced tariffs for DK home owners using more than 4000 kwh a year

### ISSUE THREAD

**Issue by rophome** [MTrab/energidataservice#589]
### Describe the feature you wish to make a request for

Home owners with electic heating get a reduced tariff on the kwh's used that extends 4000 kwh a year.

### Describe alternatives you've considered

a binary switch that triggers in ha when x kwh is exeeded in a month / year. then off then high tariff when low then...  perhaps this can be integraded in the auto tariff calculation for danish providers.

**Comment by MTrab** [comment]
This is already described in the wiki

https://github.com/MTrab/energidataservice/wiki/Template-example-for-using-reduced-electrical-fee-in-Denmark,-using-over-4000kWh-pr.-year

**Comment by rophome** [comment]
Thanks. sorry for missing that.

**Comment by PGLDK** [comment]
Apologies for reopening a closed thread. The energy companies actually calculate it on a daily basis, so everything above 11 kWh per day is exempt from taxes. Is there a way to "reconfigure" it so it calculates based on 11 kWh daily instead of 334 monthly?
