### ISSUE TITLE
FR: Mulighed for at tilføje integrationen flere gange

### ISSUE THREAD

**Issue by dykandDK** [MTrab/energidataservice#6]
Et forbedringsønske er at kunne tilføje flere sensorer,
f.eks. én med afgifter og én uden, 

Pt får man fejlen "Platform energidataservice does not generate unique IDs.", hvis man forsøger at indsætte integrationen mere end én gang - også selvom man ændrer navnet manuelt på den første enhed, der er oprettet.

Logdetaljer:

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:593 
Integration: Sensor (documentation, issues) 
First occurred: 20.00.33 (2 occurrences) 
Last logged: 20.06.59

Platform energidataservice does not generate unique IDs. ID energidataservice_East of the great belt already exists - ignoring sensor.energi_data_service_dk2_inkl_afgifter

**Comment by donnib** [comment]
Det ville være rart at kunne tilføje sensoren igen. For mit vedkommende er det ret vigtigt da jeg også regner på hvor meget jeg får tilbage af den solenergi jeg sender tilbage og der skal jeg bruge en sensor med de rå priser ;)

**Comment by MTrab** [comment]
Dette er på vej - arbejder faktisk på det lige nu og regner med at det er en del af næste release.

**Comment by donnib** [comment]
@MTrab Super fedt, Morten, jeg glæder mig ;)
