### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by AndersSpringborg** [MTrab/energidataservice#604]
### Describe the issue

When adding the integration through HACS, get this error

<img width="509" alt="image" src="https://github.com/user-attachments/assets/a462af99-31e0-487b-8892-9f1cfbadb9e0">

and this entry in my log:
```
[homeassistant.config_entries] Error occurred loading flow for integration energidataservice: No module named 'currency_converter'
```

### What version of Home Assistant Core has the issue?

2024.10.0

### What type of installation are you running?

Home Assistant Container

### Diagnostics information

I don't have diagnostics, as i can't add it

### Anything in the logs that might be useful for us?

```txt
[homeassistant.config_entries] Error occurred loading flow for integration energidataservice: No module named 'currency_converter'
```

**Comment by MTrab** [comment]
Please try reinstalling, that's a local error at your installation,  sorry
