### ISSUE TITLE
Stoped showing prices

### ISSUE THREAD

**Issue by perfrank** [MTrab/energidataservice#608]
### Describe the issue

Since this morning, EDS does not report prices, only CO2. Both Swedish and Danish prices are affected.

### What version of Home Assistant Core has the issue?

core-2024.10.1

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_energidataservice_2024-10-08T11-02-54.717Z.log](https://github.com/user-attachments/files/17292319/home-assistant_energidataservice_2024-10-08T11-02-54.717Z.log)

**Comment by MTrab** [comment]
Please add diagnostics as requested - you added the logs

**Comment by sknsean** [comment]
Nordpool is down `Server blocked request`

**Comment by perfrank** [comment]
[config_entry-energidataservice-3993ebe00cae698d2f962daf081c7195.json](https://github.com/user-attachments/files/17292457/config_entry-energidataservice-3993ebe00cae698d2f962daf081c7195.json)

**Comment by MTrab** [comment]
As this is a server error, I'll close the issue - nothing I can do about server outages
