### ISSUE TITLE
Error on reload

### ISSUE THREAD

**Issue by MSL-DA** [MTrab/energidataservice#614]
### Describe the issue

Error on reload

### What version of Home Assistant Core has the issue?

2024.10.2

### What was the last working version of Home Assistant Core?

2024.10.0

### What type of installation are you running?

Home Assistant Supervised

### Diagnostics information

```
Logger: custom_components.energidataservice.connectors.nordpool
Source: custom_components/energidataservice/connectors/nordpool/__init__.py:105
integration: Energi Data Service ([documentation](https://github.com/MTrab/energidataservice/blob/master/README.md), [issues](https://github.com/MTrab/energidataservice/issues))
First occurred: 17:43:03 (9 occurrences)
Last logged: 17:44:46

API returned error 404
```

**Comment by MTrab** [comment]
404 is an server error, indicating the API endpoint is having problems - nothing I can do about that.

**Comment by MSL-DA** [comment]
Thank you ... I had been looking for exactly that error code while you were writing. Closes it.
