### ISSUE TITLE
Nordpool API returns 404

### ISSUE THREAD

**Issue by AKoetsier** [MTrab/energidataservice#615]
### Describe the issue

Day ahead prices are no longer fetched from nordpool. Debug logging shows
`2024-10-15 15:18:03.171 ERROR (MainThread) [custom_components.energidataservice.connectors.nordpool] API returned error 404
2024-10-15 15:18:03.171 WARNING (MainThread) [custom_components.energidataservice.api] Couldn't get data from Energi Data Service, retrying in 5 minutes.`

The base-url used by the nordpool connector `https://www.nordpoolgroup.com/api/marketdata/page/10?currency=EUR&endDate=%s` no longer exists. From the looks of it a new api needs to be used. E.g. `https://dataportal-api.nordpoolgroup.com/api/DayAheadPrices?date=2024-10-16&market=DayAhead&deliveryArea=NL&currency=EUR` for NL.

### What version of Home Assistant Core has the issue?

core-2024.10.2

### What was the last working version of Home Assistant Core?

core-2024.10.2

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_energidataservice_2024-10-15T13-18-23.123Z.log](https://github.com/user-attachments/files/17378912/home-assistant_energidataservice_2024-10-15T13-18-23.123Z.log)

### Anything in the logs that might be useful for us?

```txt
2024-10-15 15:18:03.171 ERROR (MainThread) [custom_components.energidataservice.connectors.nordpool] API returned error 404
2024-10-15 15:18:03.171 WARNING (MainThread) [custom_components.energidataservice.api] Couldn't get data from Energi Data Service, retrying in 5 minutes.
```

**Comment by MTrab** [comment]
404 is a server error, meaning that Nordpool is having some errors - cannot do anything here

**Comment by AKoetsier** [comment]
Yeah I know it is a server error, it means that the page no longer exists. They also mention this in the error on the website:
`If you're searching for Market Data, you can find it on our [Data Portal](https://data.nordpoolgroup.com/).`. So the connector needs to be altered to used the (new) data portal.

**Comment by MTrab** [comment]
Okay, will reopen, but do expect the Nordpool connectornto be removed for simplification

**Comment by enoch85** [comment]
Eeh, bad move! You just removed support for bigger part of Scandinavia.

Was really promoting this integration, now I will get angry friends. :(
