### ISSUE TITLE
Not possible to choose any other than NO2 for Norway

### ISSUE THREAD

**Issue by hauard** [MTrab/energidataservice#617]
### Describe the issue

![{4671D5F4-2DCA-4457-B23F-9CBD36F51CED}](https://github.com/user-attachments/assets/55e79053-64e1-43a6-be8d-27d77e3d4d83)

When choosing price area for Norway, the only possible option is NO2, Kristiansand.

### What version of Home Assistant Core has the issue?

core-2024.10.2

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[config_entry-energidataservice-01JA93QZXH4FYGB4G7K220AJS2.json](https://github.com/user-attachments/files/17386390/config_entry-energidataservice-01JA93QZXH4FYGB4G7K220AJS2.json)

### Anything in the logs that might be useful for us?

```txt
The screenshot tells the story.
I have tried reinstalling the EDS from HACS, but no luck.
```

**Comment by MTrab** [comment]
Chwck the release notes from the latest release
