### ISSUE TITLE
400 Bad Request on the API call to https://api.energidataservice.dk

### ISSUE THREAD

**Issue by jeleniain** [MTrab/energidataservice#638]
### Describe the issue

Hi guys,
I just rebooted my container and noticed the above-mentioned issue.
Anyone else having the same problem?
Tried the rebooting and reconfiguring the integration but no success.
Thanks!

### What version of Home Assistant Core has the issue?

Latest

### What was the last working version of Home Assistant Core?

Latest

### What type of installation are you running?

Home Assistant Container

### Diagnostics information

Timestamp: 2024-11-12 21:48:57.579
Severity: ERROR
Thread: MainThread
Component: custom_components.energidataservice.connectors.energidataservice
Message: API returned error 400, Bad Request!

Timestamp: 2024-11-12 21:49:19.242
Severity: ERROR
Thread: MainThread
Component: custom_components.energidataservice.tariffs.energidataservice
Message: Error during API request: 400, message='Bad Request'
URL: https://api.energidataservice.dk/dataset/DatahubPricelist?filter=%7B%22Note%22:%5B%22Elafgift%22,%22Systemtarif%22,%22Transmissions+nettarif%22%5D%7D&limit=500

**Comment by HrCalmar** [comment]
I just added the same error.
You got me a few minutes early :-)

**Comment by rawzone** [comment]
Same problem here.

**Comment by MTrab** [comment]
Seems like an error at Energi Data Service (again), as this query, copied directly from their API documentation doesn't work either: 

`https://api.energidataservice.dk/dataset/DatahubPricelist?offset=0&start=2024-11-01T00:00&filter=%7B%22ChargeTypeCode%22:[%22IEV-NT-01%22],%22GLN_Number%22:[%225790000682102%22]%7D&sort=ValidFrom%20DESC`

**Comment by rawzone** [comment]
![image](https://github.com/user-attachments/assets/933a13be-c96e-4a3c-ae78-341adbda3793)
According to the news section on [their website](https://energidataservice.dk/news) they indeed have some sort of issue.

**Comment by Jogge** [comment]
![image](https://github.com/user-attachments/assets/795a43fd-d471-4378-a59b-58a79ce8290e)

**Comment by MTrab** [comment]
Yeah - guess they updated the news now. Wasn't mentioned earlier

**Comment by rawzone** [comment]
API access is fixed - Reload HA integration and ive gotten data back in a working state:
![image](https://github.com/user-attachments/assets/4b3ab9f5-1f00-4c29-afdb-f80de719b452)

**Comment by MTrab** [comment]
API working again.
Reload the EDS integration
