### ISSUE TITLE
Error 403 calling the api from energinet

### ISSUE THREAD

**Issue by hostrup** [MTrab/energidataservice#642]
### Describe the issue

Integration is not starting. When i check the log i can see that i get a forbidden error when trying to call this URL: 
https://api.energidataservice.dk/dataset/DatahubPricelist?filter=%7B%22Note%22:%5B%22Elafgift%22,%22Systemtarif%22,%22Transmissions+nettarif%22%5D%7D&limit=500'

I tried calling the api - without any parameters - simply calling: 
https://api.energidataservice.dk/dataset/DatahubPricelist?

Works fine.  Maybe it's something on the API side?

### What version of Home Assistant Core has the issue?

core-2024.11.2

### What was the last working version of Home Assistant Core?

core-2024.11.2

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

there is not more in that part. 

### Additional information

Not wure if it's the integration or the api?

**Comment by MTrab** [comment]
Check https://energidataservice.dk - they are apparantly down
