### ISSUE TITLE
Additional tarifs and template for additional costs seems not to work together

### ISSUE THREAD

**Issue by michael-jakobsen-dk** [MTrab/energidataservice#653]
### Describe the issue

First of. Thank you for a great integration.

I have electric heating and want to have an entity with my actual power cost without the "elafgift". I want to use this to calculate the cost of charging my EV.

My approach is to add a "complete" entity with added tarifs and in the template for additional costs to subtract the "elafgift", but I'm not getting the expected value. I'm comparing to stromligning.dk

My template is: {{"-0.941"|float}}

Example:

11-12-2024: hour 14:00
Entity with complete price: 4,651 Kr (correct compared to stromligning).
Entity with template, i.e., subtracted 0,941: 3,476kr - expected 3,71kr (4,651-0,941) - which is also the what stromligning shows.

Is my template formula wrong? Can the template and the additional tarifs not be used together, or something else?

### What version of Home Assistant Core has the issue?

2024.12.2

### What type of installation are you running?

Home Assistant Core

### Diagnostics information

[config_entry-energidataservice-01JETWEY0RK8Y9NKXY7RE5AKAP.json](https://github.com/user-attachments/files/18096628/config_entry-energidataservice-01JETWEY0RK8Y9NKXY7RE5AKAP.json)

**Comment by henriklund** [comment]
@michael-jakobsen-dk I trust that you have read [the documentation](https://github.com/MTrab/energidataservice/wiki/How-to-add-costs-of-subscription-and-delivery%3F) where it states **_ALL prices are to be entered WITHOUT VAT!_** ? Also have a look [here](https://github.com/MTrab/energidataservice/wiki/Template-example-for-using-reduced-electrical-fee-in-Denmark,-using-over-4000kWh-pr.-year). 

The correct number you should use is `0.753`, or better yet, change you template to `{{ ( 0.008 - el_afgift ) | float(0) }}`.

**Comment by michael-jakobsen-dk** [comment]
I have read some of the documentation, but apparently not all :-)

Thank you for the clarification - it works like a charm.
