### ISSUE TITLE
Trigger automation on attribute "tomorrow_valid" change

### ISSUE THREAD

**Issue by Martinnygaard** [MTrab/energidataservice#80]
### Environment:
- Home Assistant version: 2022.7.0
- Energidatastyrelsen version: 0.2.7
- Operation system: HAOS 8.2

## Describe the bug
I want to trigger an automation that will determain when to charge up my heating system buffer tank when pricesa are low.
This automation is analysing the data every hour, but it only needs to run whenever new data is comming in via energidataservice. 
I can see this data via the attribute "Tomorrow valid", but it wont trigger.

The automation trigger, that should fire whenever tomorrow_valid goes from false to true:
```
platform: state
entity_id:
  - sensor.energi_data_service
attribute: tomorrow_valid
from: 'false'
to: 'true'
id: update
```

Then I tried to setup a condition to test if tomorrow_valid is true, just to test the code - and it does not work at all. 
Condition test code:
```
condition: state
entity_id: sensor.energi_data_service
attribute: tomorrow_valid
state: 'true'
```
Here is showen the current value of the tomorrow_valid attribute:
![image](https://user-images.githubusercontent.com/26490587/180516944-2c8285bd-43ed-4c14-ab5f-9b602bccd98e.png)

The result of the condition is false. Even that it is checking if the value is true - and it appears to be true in developer tools.
![image](https://user-images.githubusercontent.com/26490587/180517177-7d4bc127-a2fd-4f80-88ac-d88cee67366b.png)

**Comment by MTrab** [comment]
Have you tried true and false without the ' ' around?

**Comment by Martinnygaard** [comment]
That apparently did the trick..... My bad then .. ;-)

Thanks for the very quick reply!
![image](https://user-images.githubusercontent.com/26490587/180517586-5bc366ef-7f58-4b4b-915d-216a01d19203.png)
