### ISSUE TITLE
[FR]: CO2 Emissions - Historic and prognosis

### ISSUE THREAD

**Issue by mikkelsiggaard** [MTrab/energidataservice#83]
First and foremost, just thank you for creating this. 

**Is your feature request related to a problem? Please describe.**
It would be great to have CO2 emissions as an option. Both as current and historic data (https://www.energidataservice.dk/tso-electricity/CO2Emis) and as a prognosis (https://www.energidataservice.dk/tso-electricity/CO2EmisProg). 
But I can't figure out if it would be best to have the whole thing as one entity or to split it up into multiple entities.
- Real time
- Historic 
- Prognosis

**Describe the solution you'd like**
I suspect this will create a rather large rewrite, since (AFAIK) it is only possible to have a single sensor value from the integration today. 
I'm unsure which HA sensor/entity type to load this in as. There might be some inspiration here: https://community.home-assistant.io/t/combine-future-and-real-time-values-in-card/403759

**Describe alternatives you've considered**
There are other people that have succeeded in doing this, but is too complicated for me to do: https://community.home-assistant.io/t/display-future-values-in-a-graph/292498

**Comment by MTrab** [comment]
I don't see this as a feature for this integration, as this is minded towards electricity prices.

**Comment by mikkelsiggaard** [comment]
Okay, and is it too much of a scope creep? 
Do you instead think it would be better to create a specific integration for CO2 Emissions?

**Comment by MTrab** [comment]
Would rather see it as a separate integration, yes.
