### ISSUE TITLE
No data for today 

### ISSUE THREAD

**Issue by Martinnygaard** [MTrab/energidataservice#87]
### Environment:
- Home Assistant version: 2022.8.1
- Energidatastyrelsen version: 0.2.7
- Operation system: HAOS

## Configuration
- Country: Denmark
- Region: West of the great belt
- Show in cents: No
- Number of decimals 3 

## Describe the bug
The Integration has worked flawlessly for weeks, and yesterday it sis not manage to poll new data in the afternoon. 

Is this a general issue or just my instance? 
I have not enabled the logger for the integration yet - but I will add it when I am at a PC later today. 

![Screenshot_20220809-061826_Home Assistant](https://user-images.githubusercontent.com/26490587/183563869-56cbf1ac-6bb1-485f-81d8-07f659e07f61.jpg)

**Comment by MartinNygaardSchacht** [comment]
I setup the logger and restarted home assistant.
Now the prices are back and all is OK.

I cant supply logs with errors in it, but I am still curious why this happened in the first place.

**Comment by MTrab** [comment]
Going to close this - been away on holidays and everything seems fine by now.
Please do create a new issue if it occurs again - the sooner the better.

**Comment by Martinnygaard** [comment]
I wont open a new, because it fixed itself again, and I still dont have any logs.
But esterday the same thing happened again. I looked in the logs, and nothing ordinary was there.

At midnight when the last piece of data got outdated, it apparently collected the new dataset. But i would say that was 11 hours to late.

I will keep monitoring it.
