### ISSUE TITLE
[FR]: Hent DKK direkte fra Energi Data Service i stedet for omregning

### ISSUE THREAD

**Issue by osos** [MTrab/energidataservice#89]
Priser i DKK er tilgængelige direkte fra datasettet, og behøver således ikke at konverteres. ("SpotPriceDKK")

Jeg har ikke tjekket den konkrete konvertering, men sammenligner priser hentet fra nordpool-plugin'et, og de priser er noget forskellige fra den du henter fra Energi Data Service, måske skyldes det konvertering.

Tænker således, at det bedre at bruge spotprisen i DKK, hvis currency faktisk er DKK.

**Comment by MTrab** [comment]
Der leveres kun udregnede DKK priser i hverdage.
Så nej, vi bliver på at hente EUR og så benytte dagens valutakurs.
Det skulle meget gerne give det samme i den sidste ende, men ved at benytte EUR er vi sikker på at få priser hver eneste dag, også i weekenderne.
